### ISSUE TITLE
Route with parameters don't work

### ISSUE THREAD

**Issue by printempw** [skipperbent/simple-php-router#104]
Here is my code:

```
<?php

require "./vendor/autoload.php";

use \Pecee\SimpleRouter\SimpleRouter as Route;

Route::get('/', function() {
    echo "index";
});

Route::get('/{foo}', function($foo) {
    echo $foo;
});

Route::start();
```

When I access "/", it works fine. But when I access the URL "http://localhost/shit", it will throw an exception:

> **Fatal error: Uncaught exception 'Pecee\SimpleRouter\RouterException' with message 'Route not found: /shit'** in E:\wwwroot\route-test\vendor\pecee\simple-router\src\Pecee\SimpleRouter\RouterBase.php:131 Stack trace: #0 E:\wwwroot\route-test\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php(24): Pecee\SimpleRouter\RouterBase->routeRequest() #1 E:\wwwroot\route-test\index.php(21): Pecee\SimpleRouter\SimpleRouter::start() #2 {main} thrown in E:\wwwroot\route-test\vendor\pecee\simple-router\src\Pecee\SimpleRouter\RouterBase.php on line 131

What's the problem?

**Comment by skipperbent** [comment]
You need to make the route optional by adding a ? `{foo?}` or place it above your other `/` route as that match before the other one is rendered.

**Comment by skipperbent** [comment]
```
<?php

require "./vendor/autoload.php";

use \Pecee\SimpleRouter\SimpleRouter as Route;

Route::get('/', function() {
    echo "index";
});

Route::get('/{foo?}', function($foo) {
    echo $foo;
});

Route::start();
```

or

```
<?php

require "./vendor/autoload.php";

use \Pecee\SimpleRouter\SimpleRouter as Route;

Route::get('/{foo}', function($foo) {
    echo $foo;
});

Route::get('/', function() {
    echo "index";
});

Route::start();
```

Should do the trick.

**Comment by printempw** [comment]
I have tried both 2 solutions you gived, but neither of them work.
just the same problem :(

**Comment by skipperbent** [comment]
@printempw 

That's really weird, I've just tried creating a project simular to yours and I got it working with the rules from your first post.

http://recordit.co/6BfYhXrHV1

1. What webserver are you using and is rewriting enabled?
2. What PHP version are you using? (I've tested 5.6 + 7.0)
3. Can you make your project work like mine (with the same parameters?).

If you are using Apache as a webserver, you can use this .htaccess to enable rewriting
```
RewriteEngine on
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteCond %{SCRIPT_FILENAME} !-l
RewriteRule ^(.*)$ index.php/$1
```

**Comment by printempw** [comment]
I'm using Nginx 1.8.0 & PHP 5.6.15. Of course rewriting is enabled and working, otherwise I won't get RouterException but a HTTP 404 error.

And it's confusing that other routing libraries work well in the same environment, e.g. NoahBuscher/Macaw

Here's my nginx config:

```
server {
    listen       3481;
    server_name  127.0.0.1 alias localhost;
    root   E:/wwwroot/bss-v3;
    index  index.html index.htm index.php;

    location ~ ^.+\.php {
        fastcgi_pass   bakend;
        fastcgi_index  index.php;
        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
        fastcgi_param  PATH_INFO $fastcgi_path_info;
        fastcgi_param  PATH_TRANSLATED $document_root$fastcgi_path_info;
        include        fastcgi.conf;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
```

**Comment by printempw** [comment]
Is there any difference between Nginx and Apache?
I will try it again with Apache.

**Comment by skipperbent** [comment]
Yeah - it's really weird, but don't worry we'll get it working on your environment too.

I'm also using the project on a production nginx (bookandbegin.com) - so it is fully compatible, we just need to find out what's happening in your case.

**This is the nginx configuration i'm using:**

I've added same route to the bookandbegin.com project and as you can see, it catches the param fine:
https://bookandbegin.com/shit
https://bookandbegin.com/
https://bookandbegin.com/tour

```php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
```

**Comment by skipperbent** [comment]
It should give you the same results - the only difference between nginx and Apache is, that on Apache you provide the rewrite-configuration in a file in the project itself - where on nginx you have to do it in the configuration.

It sure is weird the problem you are facing.. I'll try to setup an nginx with simular configuration to yours and see what happens.

**Comment by printempw** [comment]
Thanks a lot.
It seems that the rewrite rule itself is same.
It's really weird.. I will try to deploy the project to another machine to see what will happen.

**Comment by skipperbent** [comment]
@printempw 

No problem - please keep me notified if you find the source of the problem.

Remember that parameters with special characters like `-` or `_` only will be catched if you change the regular-expression for you parameter like this:

```php
Router::get('/page/{identifier}', 'TemplatesController@edit')->where(['identifier' => '([0-9a-z\_]+?)']);
```

The default regex is: `[a-z0-9]+` as far as I remember.

**Comment by printempw** [comment]
Oh.. it's really weird.

I deployed the test on my VPS, and it worked fine, all parameters were catched perfectly.
http://work.prinzeugen.net/wtf

But the same test on my local environment still keeps throwing 'Route not found' exceptions. How could it be?

**Comment by printempw** [comment]
Umm.. I required pecee/simple-router again with composer just now, and it did the trick. The route pattern ‘/{foo}’ catches parameter fine now.

But why the uri "/admin.json" couldn't be dispatched to the route pattern "/{foo}.json" correctly? It just throws exceptions like this:

```
Fatal error: Uncaught exception 'Pecee\Exception\RouterException' with message 'Route not found: /admin.json'
```

Is there any support for the routes which have parameters in middle of string like "/{foo}.json"?

**Comment by skipperbent** [comment]
@printempw 

Coooool! I'm really glad you got it working! Nice work!

Unfortunately parameters with that style weren't supported in versions below 1.7.4.0 - but thanks to you I've implemented support for that as-well - so please do a `composer update` to update to the latest version (1.7.4.0) which supports that functionality.

Please let me know if you experience any issues with the release and thanks for contributing with the project, that really means alot 👍 

**Here's the full changelog:**

- Optimized the way parameters are parsed as a result, simple-router now supports routes like `/{param1}-{param2}.json`.

- Replaced reg-ex for parameter-matching with `\w` which means that default parameter matching on routes now include `_` (underscore) per default.

- Simplified `MiddlewareTest` class.

- Added contributing site in Readme.

- Simon

**Comment by printempw** [comment]
Oh yeah, thank you!
I've updated to v1.7.4.2, and everything works perfectly now! 
Awesome! (*ﾟ∇ﾟ)

**Comment by skipperbent** [comment]
@printempw 

Great! 

I'm happy to hear!

Please let me know if you experience any issues etc.

\- Simon
