### ISSUE TITLE
Trying to use your library but didnt get work properly.

### ISSUE THREAD

**Issue by rjolive24** [skipperbent/simple-php-router#109]
Hello 

When i placed your library in my project . and set routes . Every time i got route not found error. 
Can you please give proper information for initialize and setup it.

Thank you

**Comment by skipperbent** [comment]
Hi,

What kind of webserver are you using? You need to make sure that url-rewriting is enabled and pointing to the php file which initializes the routing (usually the index.php).

I will update the documentation to clearly define how to setup url-rewriting for both Apache and Nginx servers.

**Comment by rjolive24** [comment]
Hello sir,

I tried your library in apache in localhost. But still its not working..
Getting some issues with code. Htaccess rule is working fine. But found the
issue with callback methods. When i set controller with namespace it's
always give me 404 error.

Warm Regards.
Rj

**Comment by skipperbent** [comment]
All right sounds like the setup you are using should be working then.

If you can provide some of the code which you are experiencing issues with then I can perhaps help you out :)

You should get a routerexception and not an Apache 404 if the namespace or path is not found unless you've setup a error handler to handle that.

- simon

**Comment by skipperbent** [comment]
Hello again,

We've included a demo-project in the project and some instructions on how to get started.
https://github.com/skipperbent/simple-php-router/tree/master/demo-project

Please create a new issue if you have further questions or problems.
