### ISSUE TITLE
ask - json support

### ISSUE THREAD

**Issue by kelaskakap** [skipperbent/simple-php-router#115]
Hi,
could you add json support for post/put/patch/delete?

Thank you.

**Comment by skipperbent** [comment]
Can you please specify what you mean by json support?

If you want your urls to contain something like `/api/posts.json` you can do so by using the `match` option and create your own regular expression match for the entire url.

**Pseudo example:**

```php
Router::put('/posts', 'PostController@update')->match('([A-Za-z0-9\\/]+)\.json');
```

**Comment by skipperbent** [comment]
Closing due to no replies. Please open again if you have any further questions.
