### ISSUE TITLE
accept body with json format (post/put/patch/delete)

### ISSUE THREAD

**Issue by kelaskakap** [skipperbent/simple-php-router#126]
Hi, sorry, I just noticed yesterday. So the previous issue I addressed https://github.com/skipperbent/simple-php-router/issues/115

I want to send body with json format from post method. something like:
`
$.ajax {
url: /book/insert
method: 'post',
type: 'json'
}
`
I want to make `/book/insert` endpoint with post method and able to accept body with json format.

**Comment by skipperbent** [comment]
No problem. You can easily do that.

1. Add a rule to your `routes.php` etc.

```php
SimpleRouter::post('/book/insert', 'BookController@insert');
```

Though I would recommended you used the `resource` method instead if you are creating REST functionality - it would however conflict with the url given in your example:

```php
SimpleRouter::resource('/books', 'BookController');
```

In your controller you can use the `response` function to output json:

```php
// if you have added helper functions - see documentation on helper functions
response()->toJson($books);

// otherwise
\SimpleRouter::response()->toJson($books);

```

-- also --

You could create a json exception handler to manage your exceptions, this is great if you have multiple endpoints that requires validation etc and you want an easy way to handling the json output when an error occurs.

Then I would add something like this to my `routes.php`

```php
Router::group(['prefix' => '/books', 'exceptionHandler' => '\namespace\MyJsonExceptionHandler'], function() {
        Router::post('/insert', 'BooksController@insert');
});
```

and then in the `MyJsonExceptionHandler` class

```php
class ExceptionHandler implements IExceptionHandler  {

    public function handleError(Request $request, RouterEntry $router = null, \Exception $error) {

            response()->json([
                'error' => $error->getMessage(),
                'code' => $error->getCode()
            ]);

	}

}
```

In your controllers you can then just throw an exception if validation etc. fails.

**Comment by skipperbent** [comment]
Also version 1.8.0.8 and above supports gettings request data from json like this

```php
// get all elements
$data = input()->all();

// or filter by key
$username = input()->all(['username']);
```

**Comment by kelaskakap** [comment]
thank you :)

**Comment by skipperbent** [comment]
No problem - i'll close this ticket for now. Please open another ticket if you've got any further questions or issues :)
