### ISSUE TITLE
problem slug contain dashes

### ISSUE THREAD

**Issue by Voronov** [skipperbent/simple-php-router#206]
Hi. Thanks  for your work. 
I have an error if slug contain dashes
Fatal error: Uncaught exception 'Pecee\SimpleRouter\Exceptions\NotFoundHttpException' with message 'Route not found
I tried to work with  method where, but I have problem even with code from example.
SimpleRouter::get('/user/{name}', function ($name) {
    //
})->where(['name', '[A-Za-z]+']);
shows
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php on line 405
Can you check this please
With Regards, Sergey.

**Comment by skipperbent** [comment]
Hello @Voronov ,

Thank you for your feedback.

The issue has been resolved in version 2.6.4.

If you are unable to update, you can use the `setWhere` method instead, as the `where` alias-method was broken in the previous release, causing an infinite loop.

Please re-open the ticket if the new release does not fix your issue and/or if you have any further questions.

/Simon
