### ISSUE TITLE
subfolder problem

### ISSUE THREAD

**Issue by AybimYazilim** [skipperbent/simple-php-router#211]
hi,

i wanna use this in subfolder in my host.
but there is no auto detect system.

example 
adress : localhost/AybimCms/admin
router :
SimpleRouter::group(['prefix' => 'AybimCms/admin/'], function () { 
SimpleRouter::get('/', 'Home@index')->name('adminpanel');
}

then i want to redirect " localhost/AybimCms/admin"  with url('adminpanel') function but redirect to "localhost/admin"

how can i fix it

**Comment by skipperbent** [comment]
Hello.

You can easily redirect like this:

```php
SimpleRouter::group(['prefix' => 'AybimCms/admin/'], function () {
    response()->redirect('/');
});
```

Alternatively you could create a middleware and put the authentication logic in there.

Example:

```php
SimpleRouter::get('/', 'DefaultController@home')->name('home');

SimpleRouter::group(['prefix' => 'AybimCms/admin/', 'middleware' => 'Project\Middleware\AdminAuthentication'], function() {
    SimpleRouter::get('/', 'AdminController@home');
});
```

And then check for correct authentication within your middleware - and redirect if it was unsuccessful.

```php
class AdminAuthentication implements IMiddleware
{
	public function handle(Request $request, ILoadableRoute &$route)
	{
		// Do authentication and redirect if user is not authenticated
                if($user->isUserAuthenticatedOrNot === false) {
                     response()->redirect(url('home'), 403);
                }

                // Otherwise set user-data on the request object
                $request->user = $user;
	}
}
```

Now you know that the user will always be authenticated when hitting `/AybimCms/admin` and the user-data will always be available by calling `request()->user`.

**Comment by AybimYazilim** [comment]
Thanks a lot for ur support

Have a nice day
