### ISSUE TITLE
Resources Problem in v3.2.0

### ISSUE THREAD

**Issue by AybimYazilim** [skipperbent/simple-php-router#227]
SimpleRouter::resource('/m11', 'DoktorController')->name('doktor'); // Doktorlar
        SimpleRouter::resource('/m1', 'KurumsalController')->name('kurumsal'); // Kurumsal
        SimpleRouter::resource('/m2', 'HizmetController')->name('hizmet'); // Hizmetler
        SimpleRouter::resource('/m3', 'ProjeController')->name('proje'); // Projeler
        SimpleRouter::resource('/m4', 'ReferansController')->name('referans'); // Projeler
        SimpleRouter::resource('/m5', 'BlogController')->name('blog'); // Blog
        SimpleRouter::resource('/m6', 'VideoController')->name('video'); // Video
        SimpleRouter::resource('/m7', 'FotoController')->name('foto'); // Foto Galeri

I updated version v3.2.0. But my resources not working :(

And then I again downgrade 3.1.1  and there is no problem. 

How i can fix it ?

**Comment by skipperbent** [comment]
Hi @AybimYazilim 

This issue has been resolved in the latest version (3.2.1), available here:
https://github.com/skipperbent/simple-php-router/releases/tag/3.2.1

Thanks for reporting the issue!

/ Simon

**Comment by AybimYazilim** [comment]
Thanks :)
