### ISSUE TITLE
.htaccess?

### ISSUE THREAD

**Issue by DandersenCode** [skipperbent/simple-php-router#232]

**Comment by skipperbent** [comment]
Sorry if the documentation is unclear on this point. The .htaccess section was copy pasted from the demo-project repo.

I'll update the documentation with examples here, in the meantime you can find the correct `.htaccess` file in the `public` folder here:

https://github.com/skipperbent/simple-router-demo

**Comment by skipperbent** [comment]
This issue has been resolved. Please feel free to reopen or create another ticket. 

Thanks for your feedback, I really appreciate your feedback.
