### ISSUE TITLE
Handle 404 Page

### ISSUE THREAD

**Issue by zaingithub** [skipperbent/simple-php-router#238]
Hi, thanks for this powerfull simple Routing. I have use your routing for my sites.

After i implement a routing to handle 404, like i did in laravel : 

SimpleRouter::all( '{notfound}', 'AdminController@404notfound' )->where( [ 'notfound' => '(.*)'] );

where the function 404notfound() inside AdminController is ;

	function 404notfound() {
	       header("Location: " . home_url() );
	       exit();	
	}

Why it causing a 302 status header for all of my routing, including homepage, single page, and also another. Please help me...

I cannot find any documentation on handling 404 request to return to homepage, thanks.

**Comment by skipperbent** [comment]
Hello. 

Thanks for your feedback - I'm really glad that you find the project useful. 

There is no shortcut for handling 404, 403 etc. You need either need to add a custom exception handler and handle the NotFoundHttpException and use the router to redirect the request to either another URL or a controller / method. 

Please refer to the exception part of the documentation for further details. I will provide an example when I'm back at my computer (writing this on the phone). 

/ Simon

**Comment by zaingithub** [comment]
OK Thank you, i am waiting for it :)

**Comment by skipperbent** [comment]
I'll add an easy option to add a 404-path in a future release, until then please use a custom `ExceptionHandler` and do something like shown in the documentation:

https://github.com/skipperbent/simple-php-router#example-1

### ExceptionHandler

```php
namespace Demo\Handlers;

use Pecee\Handlers\IExceptionHandler;
use Pecee\Http\Request;
use Pecee\SimpleRouter\Exceptions\NotFoundHttpException;

class CustomExceptionHandler implements IExceptionHandler
{
	public function handleError(Request $request, \Exception $error)
	{

		/* Set the rewrite callback if the page is not found */
		if($error instanceof NotFoundHttpException) {

			// Render custom 404-page from your custom controller + method
			$request->setRewriteCallback('Demo\Controllers\PageController@notFound');
			return $request;

		}

                // Otherwise throw the error
		throw $error;

	}

}
```

**You can also redirect to another path by using:**

```php
$request->setRewriteUrl(url('home'));
return $request;
```

**Remember to add your custom `ExceptionHandler` to your `routes.php` file:**

```php
Router::group(['exceptionHandler' => Demo\Handler\CustomExceptionHandler::class], function() {

      // Your routes go here

});
```

I'll update this ticket once an easier way to add 404-handling has been implemented to the router.

Feel free to reply or create more tickets if you have any further ideas or questions.

/ Simon

**Comment by zaingithub** [comment]
Thank you, i am waiting for the next update :)
I don't know exactly how can i use your example. I am newbie, still learning the code, hehe

**Comment by skipperbent** [comment]
@zaingithub 

You can find examples on the router demo project, located here:
https://github.com/skipperbent/simple-router-demo

What you want is to create your own exception-handler. Look at the `CustomExceptionHandler` class example (read the inline comments for more info) located here:
https://github.com/skipperbent/simple-router-demo/blob/master/app/Handlers/CustomExceptionHandler.php

And then you just register your new class in your routes file like this:
```php
Router::group(['exceptionHandler' => 'Demo\Handlers\CustomExceptionHandler'], function () {
	
    // Your routes here

});
```

**Comment by skipperbent** [comment]
Hello.

The new version of simple-php-router contains changes that makes it easier to handle errors (404, 403 etc) within your project.

Please refer to this section of the documentation:
https://github.com/skipperbent/simple-php-router#exceptionhandlers

**Example**

The example below should be placed in the file that contain all your routes. What happens is that `Router::error` takes a callback function that are fired when an error occurs in simple-php-router. This is useful if you want to catch a 404 etc. 

Below I've written an small example that simply redirects to the url `/not-found` if an Exception of the type `NotFoundHttpException` (404).

```php
// ... your routes.php file ...
Router::get('/not-found', 'PageController@notFound');

Router::error(function(Request $request, \Exception $exception) {
    if($exception instanceof NotFoundHttpException) {
        response()->redirect('/not-found');
    }
});
```

I'll close the issue for now. Please feel free to create another ticket if you need any further assistance.

/ Simon

**Comment by kztneda** [comment]
Hello.

IDK what I'm doing wrong but I can't get the error handling working well. I've placed all the routes as simple as possible to try the error get working but I can't. The normal routes work well just the error handling don't.

Here is my Routes file.
```PHP
  namespace Routes;
  use \Pecee\SimpleRouter\SimpleRouter as Router;
  
  include_once 'Controls/Errors.php';

  Router::get('/', function() {
      return 'Hello world';
  });
  Router::get('/{id}', function($id) {
      return $id;
  });
  Router::get('/App/{id}', function($id) {
      return $id;
  });
  
  Router::get('/not-found', 'Errors@notFound');
  Router::error(function(Request $request, \Exception $exception) {
      if($exception instanceof NotFoundHttpException && $exception->getCode() === 404) {
          return response()->redirect('/not-found');
      }
  });
```

here is what I have on "Controls/Error.php"
```PHP
namespace Controls;

class Errors
{
    public function notFound():string{
        return "Not found";
    }
}
```

I always get this error instead of the error handle response I want:
`Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/asd/asd/s/" in **PATH TO LIB**\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php:450 Stack trace: #0 **PATH TO LIB**\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php(339): Pecee\SimpleRouter\Router->routeRequest() #1 **PATH TO LIB**\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php(68): Pecee\SimpleRouter\Router->start() #2 **PATH TO LIB**\Pecee\SimpleRouter\SimpleRouter::start() #3 **MAIN PATH**\index.php(20): Router::read(false) #4 {main} thrown in **PATH TO LIB**\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 450`

Here is my index.php
```PHP
require_once '**PATH TO LIB**/Router.php';
Router::read(false);
```

Here is '**PATH TO LIB**/Router.php'
```PHP
require_once '**PATH TO LIB**/vendor/autoload.php';
use \Pecee\SimpleRouter\SimpleRouter;

class Router extends SimpleRouter 
{
    public static function read($isRunningLocally)
    {
        $prefix = ($isRunningLocally) ? '/test' : null;
        static::group(['prefix' => $prefix], function() {
            require_once 'Routes.php';
        });
        parent::start();
    }
}
```

Could you please help me guys?.
