### ISSUE TITLE
Error on converting callback to string

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#239]
Hi,

When using getUrl() in a named url with a anonymous function, throws one error on `getMethod()`, at line 268 of `src\Pecee\SimpleRouter\Route\Route.php`

I have changed the code to:

```
    public function getMethod()
    {
        if (is_string($this->callback) && strpos($this->callback, '@') !== false) {
            $tmp = explode('@', $this->callback);

            return $tmp[1];
        }

        return null;
    }

    public function getClass()
    {
        if (is_string($this->callback) && strpos($this->callback, '@') !== false) {
            $tmp = explode('@', $this->callback);

            return $tmp[0];
        }

        return null;
    }
```

**Comment by skipperbent** [comment]
Thanks for reporting the issue, I really appreciate it. 

I'll change all simular references to ensure that the value is a `string` before checking for the `@` character. The fix will be available in the upcoming release.

**Comment by skipperbent** [comment]
The latest version (3.3.1) has been fixed. 

Thanks for reporting this issue. If you have any further questions, experience or need assistance, feel free to create another ticket or reopen this.

/ Simon

**Comment by jatubio** [comment]
Nice to help you to make a better route library ;)
