### ISSUE TITLE
'Route not found' error shows original route instead rewrited route

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#240]
If i use one `RouterBootManager` to rewrite routes using `request->setRewriteUrl()` to rewrite one url and the new url have a route not defined, the error message tell me about not found original route.

Sample:

I will rewrite `/page/login` to `/ask/login`, but i don't have defined route for `/ask/login`.

I get this error:

```
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: /page/login in ..\pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 286
```

I will be better:

```
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: /ask/login (redirected from /page/login) in ..\pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 286

```
Or:

```
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: /ask/login in ..\pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 286

```

**Comment by skipperbent** [comment]
Hi @jatubio. 

I totally i agree with you. Some knowledge about the current route would be very useful for faster debugging. 

I'll add this feature in the upcoming release.

Thanks for providing your feedback, I really appreciate it. 

/ Simon

**Comment by skipperbent** [comment]
Hi @jatubio .

The lastest version (3.3.1) will now the last redirected/rewritten rule if available.

Thanks for taking your time to contribute your ideas to this project.

If you need any further assistance, have feedback or ideas - feel free to create another ticket and/or reopen the existing.

/ Simon

**Comment by jatubio** [comment]
Hi @skipperbent.

Thank you for this great library and to take feedback into account. Happy to help
