### ISSUE TITLE
PHP 5.6 feature used in code

### ISSUE THREAD

**Issue by thexeos** [skipperbent/simple-php-router#244]
The library lists PHP 5.5 as supported version, but there is a `ARRAY_FILTER_USE_KEY` constant used in [`Pecee\Http\Input\Input`](https://github.com/skipperbent/simple-php-router/blob/bc0349010056ac6c8ee469d791f91b6ee9c1b140/src/Pecee/Http/Input/Input.php#L291) that was [added in PHP 5.6](http://php.net/manual/en/function.array-filter.php#refsect1-function.array-filter-changelog).

**Comment by skipperbent** [comment]
Hi @thexeos .

Thanks for your feedback. You're right the library is no longer compatible with PHP 5.5, the documentation haven't been corrected yet. 

However if you don't need the features that the `Input` class provides, the router should work just fine.

If you want PHP 5.5 compatibility please let me know and I'll add those changes to the next release.

/ Simon

**Comment by thexeos** [comment]
Hey @skipperbent 

This is the only incompatibility with PHP 5.5 I've found so far.

I've patched my local version with PHP 5.5 compatible `array_intersect_key`. I've written a small benchmark: 
[intersect-filter-bench.php](https://github.com/skipperbent/simple-php-router/files/1150696/intersect-filter-bench.txt)

The results for 5.5:

> 100K intersect @ beg: 0.11990714073181ms
> 100K intersect @ end: 0.11870408058167ms
> 100K intersect @ rnd: 0.086306810379028ms

And for 5.6:

> 100K intersect @ beg: 0.11825489997864ms
> 100K filter @ beg: 1.5999159812927ms
> 100K intersect @ end: 0.12499189376831ms
> 100K filter @ end: 1.5521810054779ms
> 100K intersect @ rnd: 0.089372873306274ms
> 100K filter @ rnd: 1.2979729175568ms

And for 7.0:

> 100K intersect @ beg: 0.065983057022095ms
> 100K filter @ beg: 0.35533285140991ms
> 100K intersect @ end: 0.067379951477051ms
> 100K filter @ end: 0.3432469367981ms
> 100K intersect @ rnd: 0.039260149002075ms
> 100K filter @ rnd: 0.53100085258484ms

So changing to `$output = array_intersect_key($output, array_flip($filter));` would produce about one order of magnitude gain. Obviously a micro-optimization, but in this case it returns the support for 5.5, at least in the Input class.

The difference in execution time is mainly caused by the time penalty of internal context switching for every callback function invocation. PHP 7 is better at it, but it's still slower than "native" code that is used by built-in functions.

**Comment by skipperbent** [comment]
The PHP 5.5 compatibility has been fixed in version 3.3.2.

Thanks for your support, I really appreciate it. If you need assistance or experience problems - let me know and I'll do all I can to help you out.

/ Simon
