### ISSUE TITLE
Parameters are NULL if the route contains '-' for param value.

### ISSUE THREAD

**Issue by mihutz92** [skipperbent/simple-php-router#249]
oHello,
I found a problem (I think) when trying to create some routes dynamically. 

Ex: 
Route /p/{any}/{id}
/p/word/{id} -> returns: "word"
/p/another-word/{id} -> returns "null"

I want to match the route "p/my-cat-is-beatiful/1" and use the {id}=1 in order to show the content I want.

I read about "Bootmanager: loading routes dynamically", but I don't want to write all the routes there because I have 1,8 million..

I also tried with setMatch() method, but the results are the same.

```
SimpleRouter::get('/ajax/{any}', function($param1) {
    var_dump($param1);
})->setMatch('/\/ajax\/([^.]*[^.]*)/is');
```
$param1 = null when the "any" part from the route contains "-".
Is there any way to avoid this? 

Thanks,
Claudiu

**Comment by mihutz92** [comment]
Please ignore!!! I found a way 👍 .

`
SimpleRouter::get('/ajax/{any}', function($any) { echo $any;}, ['defaultParameterRegex' => '[\w\-]+']);
`

**Comment by skipperbent** [comment]
Hello @mihutz92 

Thanks for taking your time to report your feedback.

There's a section in documentation explaining how to customize the regular expression used for matching parameters along with an explanation on why it only matches the `\w` pattern. It's hidden in the Advanced section of the documentation.

To avoid any confusion in the future, I'll move the section to the "Route parameters" section of the documentation.

I'm glad you got it working.

/ Simon
