### ISSUE TITLE
The library does not work

### ISSUE THREAD

**Issue by alejoloe007jb** [skipperbent/simple-php-router#253]
not work:

use Pecee\SimpleRouter\SimpleRouter as Route;
Route::get('/', function () {
    echo 'Hola';
});
Route::get('/profile/{id?}', function ($id) {
    echo $id;
});
Route::start();

Yes work:

use Pecee\SimpleRouter\SimpleRouter as Route;

Route::get('/profile/{id?}', function ($id) {
    echo $id;
});
Route::get('/', function () {
    echo 'Hola';
});
Route::start();

**Comment by skipperbent** [comment]
Hi @alejoloe007jb .

Thanks for reporting the issue!

The problem has been resolved in version 3.3.4. Please update your project to the latest version.

If you have any further problems or issues, feel free to reopen or create a new issue.

/ Simon
