### ISSUE TITLE
NotFoundHttpException if route parameters are 'encoded'

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#261]
Hi Simon,

I'm using your library on one spanish web site. 

For the route: `/especialidad/{especialidad}`
Sometimes i have one url like: `/especialidad/cirugía local`. 
I have encoded the url and final url is: `/especialidad/cirug%C3%ADa%20local`, but i get NotFoundHttpException with this url.

In summary:

This works:
`/especialidad/cirugia`

This don't work:
`/especialidad/cirug%C3%ADa (/especialidad/cirugía)`
`/especialidad/cirug%C3%ADa%20local (/especialidad/cirugía local)`

Thank you

**Comment by skipperbent** [comment]
Hi @jatubio .

I will make some unit tests and see what I can do about the issue you are experiencing.

Until then you might be able to create your own workaround by defining your own regular expression for the parameters. By default the library uses only `\w` which matches `A-Z`, `0-9` and a limited set of special characters.

Please refer to the "Custom regex for matching parameters" section in the documentation for further information:
https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

I think something like this could work (haven't tested):
`[\w\%]+`

I'll keep you posted when I've got further info.

/ Simon

**Comment by jatubio** [comment]
Hi @skipperbent.

I have tested the url `/cursos/listado/especialidad/Cardiolog%C3%ADa` with `SimpleRouter::('cursos/listado/{listado?}/{filtro?}', $callback, ['defaultParameterRegex' => '[\w\%]+'])` but it don't work.

Maybe this can help you:
- If i write `/cursos/listado/especialidad/Cardiolog%C3%ADa`, i get `/cursos/listado/especialidad/Cardiología` on php logs. Then, maybe you can add `/u` flag to parameter regex to support unicode letters.

But, it's not a complete solution because `%20` for spaces.

Simon, Thank you for your time.

**Comment by skipperbent** [comment]
Hi @jatubio .

Can you please try this regular expression the affected routes? 
It will support spanish letters and accents, and in my testing it seem to pass on the routes you have issues with.

```php
SimpleRouter::get('cursos/listado/{listado?}/{filtro?}', $callback, ['defaultParameterRegex' => '[\w\p{L}\s-]+']);
```

No worries - I always appreciate feedback which helps improve the project, so keep em' coming 👍 

Let me know if the above works.

/ Simon

**Comment by skipperbent** [comment]
Copy-pasta of passing unit-test:

```php
public function testUnicodeCharacters()
{
    TestRouter::get('/cursos/listado/{listado?}/{category?}', 'DummyController@method1', ['defaultParameterRegex' => '[\w\p{L}\s-]+']);
    TestRouter::get('/kategori/økse', 'DummyController@method1', ['defaultParameterRegex' => '[\w\ø]+']);

    TestRouter::debugNoReset('/cursos/listado/especialidad/cirugía local', 'get');
    $this->assertEquals('/cursos/listado/{listado?}/{category?}/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());

    TestRouter::debugNoReset('/kategori/økse', 'get');
    $this->assertEquals('/kategori/økse/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());

    TestRouter::router()->reset();
}
```

**Comment by jatubio** [comment]
Thank you @skipperbent, it works like a charm! :)

**Comment by skipperbent** [comment]
I'm glad to hear. I'll close this issue.

/ Simon
