### ISSUE TITLE
Asking for getUrl() without parameters but getting with current route parameters

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#262]
Hi simon,

This is what it's happening to me:

I have one route named 'listados' with the regex: `/cursos/listado/{listado?}/{filtro?}/`

I go on the browser to url `/cursos/listado/especialidad/test/`

If I run `router()->getUrl('listados', ['full','one'])` I get: `/cursos/listado/full/one/`.
But, if I run `router()->getUrl('listados', [])` I am getting: `/cursos/listado/especialidad/test/` when I expected to get only `/cursos/listado` (without parameters).

The problem seems to be on `LoadableRoute->findUrl()`, who adds the parameters of the current path if $parameters is empty.

**Comment by skipperbent** [comment]
Hi @jatubio .

There's already a fix that should resolve this issue which will be available in the next release. The next release will be ready shortly - I'll keep you posted.

/ Simon

**Comment by skipperbent** [comment]
Please try updating to version 3.3.6 and see if your issue has been resolved. :)

/ Simon

**Comment by skipperbent** [comment]
Hi @jatubio .

Are you still experiencing issues with version 3.3.6?

**Comment by jatubio** [comment]
Sorry @skipperbent , have no time to test it.

I will tell you later

**Comment by jatubio** [comment]
Ho @skipperbent 

It's solved on version 3.3.6.

Thank you a lot.

It is great to use a library where the author is checking the problems and solving them. :)

**Comment by skipperbent** [comment]
@jatubio Thank you for the kind words and thanks for reporting the issue and using the library.
