### ISSUE TITLE
Use getHeader('unencoded_url') for IIS instead of $this->getHeader('request-uri')

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#268]
Hi simon,

I'm using IIS and i'm not sure if this issue happens also on Apache and another Web Servers.

When i have one url with utf8 characters, like: `http://www.misite.com/especialidad/Dermatolog%C3%ADa` or `http://www.misite.com/especialidad/Dermatología`, i'm getting a strangely encoded version of `Dermatología`, but not `Dermatología` or `Dermatolog%C3%ADa`

Strangely, for something like `http://www.misite.com/?especialidad=Dermatolog%C3%ADa` or `http://www.misite.com/?especialidad=Dermatología` i get `Dermatología` or `Dermatolog%C3%ADa` for `$_GET['especialidad']`

I've researched and, apparently, IIS encodes somehow the part that corresponds to the path of the url, but not on querystring part.

You can get more information here: https://github.com/tjanczuk/iisnode/pull/486 and here: https://forums.iis.net/t/1153679.aspx

Then, i have made this change on __construct() method of Peece\Http\Request class:
`$this->uri = urldecode($this->getHeader('unencoded_url')) ?: $this->getHeader('request-uri');`

And it's working like a charm.

`unencoded_url` seems to be present only when url contains utf8 characters.

**Comment by skipperbent** [comment]
Thanks for mentioning this - haven't done a lot of testing on IIS to be honest, so I'm glad you're with us to ensure everything runs perfectly for those that uses IIS. 

I don't think your change will break anything and as long as the unit tests passes I see no problem in releasing your fix.  However we might need to check all the references in the router classes to ensure that `urldecode` is not called twice and change your operator check so it's compatible with php 5.6.

Great work! I'll add this to the next release and keep you posted. 

/ Simon

**Comment by jatubio** [comment]
It is always a pleasure to help :)

**Comment by jatubio** [comment]
After decode the url, I need to remove accents from some parameters.

If I add this line to `__construct()` method of `Peece\Http\Request` class:
`$this->uri=removeacents($this->uri);`

Like that:
```
$this->uri = urldecode($this->getHeader('unencoded_url')) ?: $this->getHeader('request-uri');
$this->uri=removeacents($this->uri);
```

It works ok and for `http://www.misite.com/especialidad/Dermatolog%C3%ADa` or `http://www.misite.com/especialidad/Dermatología` I get `http://www.misite.com/especialidad/Dermatologia`

But, if i don't add these line and try to do this:
$parameter=removeacents(request()->getLoadedRoute()->getParameters['especialidad']) i'm getting the word 'Dermatología' oddly coded.

¿This it's because something is changing the uri or parameters code after `__construc()` method?

**Comment by skipperbent** [comment]
Urldecode might change the encoding, so you have to remove urldecode from the route classes which uses request->getUri() otherwise they will be decoded twice. 

You can see the classes you need to change in the commit to referenced above.

**Comment by jatubio** [comment]
I have put the same changes on my code, but don't have distinct results.

This is from my log (v.3.3.6):

On `Request->__construct()`:
```
   $this->getHeader("request-uri"):/cursos/listado/especialidad/Dermatolog韆
   $this->getHeader("unencoded_url"):/cursos/listado/especialidad/Dermatolog%C3%ADa
   urldecode($this->getHeader("unencoded_url")):/cursos/listado/especialidad/Dermatolog铆a
```

Only `Dermatolog铆a` seems to work with removeAcents() function. Then, I can't get `request-uri`, I have to get `unencoded_url` and on some moment do a urldecode().

If I left this line, I get this results for getParameter():
`$this->uri = $this->getHeader('request-uri'); --> /cursos/listado/especialidad/Dermatolog韆`
`getParameter() --> Dermatolog韆`
`$this->uri = $this->getHeader('unencoded_url'); --> /cursos/listado/especialidad/Dermatolog%C3%ADa`
`getParameter() --> Dermatolog胈a`
`$this->uri = urldecode($this->getHeader('unencoded_url')); --> /cursos/listado/especialidad/Dermatolog铆a`
`getParameter() --> Dermatolog胈a`

As you can see, something strange happens: the parameter is changed on the second and third tests, but not in the first.

PS: If I left only this line: `$this->uri = $this->getHeader('unencoded_url') ?: $this->getHeader('request-uri');`, i get `Route not found: "/cursos/listado/especialidad/Dermatolog%C3%ADa" ` with the changes of your referenced commit.

**Comment by skipperbent** [comment]
Did some digging and it turns out that PHP's `parse_url` function doesn't work well with unicode characters.

Did some tests and managed to get it working with a custom url parser. I'll update the pull-request shortly so you can see what's changed.

**Comment by skipperbent** [comment]
The fix is available here and is pending next release:
https://github.com/skipperbent/simple-php-router/pull/271/files

Note the new `Uri` class and especially the `parseUrl` method. Also all references to the old php `parse_url` has been removed.

**Comment by jatubio** [comment]
I'm testing only the last pull files and is not working ok. I will wait to your next relase to test them :)

**Comment by skipperbent** [comment]
It should work - the unit tests with your example returns the correctly encoded characters. 

Try the latest version 3.4.0, please read the release notes before updating as some changes might break your project.

**Comment by jatubio** [comment]
Now, with 3.4.0, `http://www.site.com/cursos/listado/especialidad/Dermatología` will go to default route, but 
`http://www.site.com/cursos/listado/especialidad/Dermatologia` it's working ok and go to correct route.

This is my `['defaultParameterRegex' => '[\(\)\w\p{L}\s-]+']` (I have added '(' and ')' because have some words with them.

I will try to pass your tests. Last time I tried don't know how to setup phpunit correctly, but now I will try again and tell you.

**Comment by skipperbent** [comment]
Setting up phpunit is easy. You just run composer install in the simple-php-router directory, then PhpStorm should detect everything automatically.

Sounds like you should consider using querystrings instead as they are guaranteed to support all characters. If you send unicode characters via the path - browser might send them differently to your server.

This unit-tests passes - and the parameters returned are correct.

```php
public function testUnicodeCharacters()
    {
        // Test spanish characters
        TestRouter::get('/cursos/listado/{listado?}/{category?}', 'DummyController@method1', ['defaultParameterRegex' => '[\w\p{L}\s-\í]+']);
        TestRouter::debugNoReset('/cursos/listado/especialidad/cirugía local', 'get');
        $this->assertEquals('/cursos/listado/{listado?}/{category?}/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());

        // Test danish characters
        TestRouter::get('/kategori/økse', 'DummyController@method1', ['defaultParameterRegex' => '[\w\ø]+']);
        TestRouter::debugNoReset('/kategori/økse', 'get');
        $this->assertEquals('/kategori/økse/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());

        TestRouter::get('/test/{param}', 'DummyController@method1', ['defaultParameterRegex' => '[\w\p{L}\s-\í]+']);
        TestRouter::debugNoReset('/test/Dermatología');

        $parameters = TestRouter::request()->getLoadedRoute()->getParameters();

        $this->assertEquals('Dermatología', $parameters['param']);

        TestRouter::router()->reset();
    }

```

**Comment by jatubio** [comment]
I have phpunit installed, but not PhpStorm :(

When I run `phpunit.cmd --bootstrap .\vendor\autoload.php %* .\vendor\pecee\simple-router\test` I get always `PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in ...\last\vendor\pecee\simple-router\test\GroupTest.php on line 7`

**Comment by jatubio** [comment]
Ok, don't know why i will not have a good version of your composer.json file. I have downloaded and now it's installing phpunit

**Comment by skipperbent** [comment]
Unfortunately never used PhpUnit outside of PhpStorm so can't help you on that part. However this is the command that PhpStorm runs:

"C:\Program Files (x86)\XWM\php\php-7.0.3\php.exe" C:/Users/simon/AppData/Local/Temp/ide-phpunit.php --no-configuration D:\Workspace\simple-php-router\test

**Comment by skipperbent** [comment]
Btw try adding `\í` to your defaultParameterRegex.

**Comment by skipperbent** [comment]
Think i solved your issue in problem 3.4.1 where I've added unicode regex support, so now the regex below should match all foreign characters.

After updating, try using this parameterRegex:

`['defaultParameterRegex' => '[\w\p{L}\s-]+']`

or
`['defaultParameterRegex' => '[\w\x00-\x7F]+']`

**Comment by jatubio** [comment]
I finally got it to work on 3.4.1 version!!

I need to add '%' to defaultParameterRegex. This is my updated `['defaultParameterRegex' => '[\%\(\)\w\p{L}\s-]+']`

But, the first difficult was that, indeed the tests are executed without problems. But it's because when running the tests, the code on `Request->__construct():` is not runned.

If you want this project to be compatible with IIS, you have to add this modification:
```
        if(!empty($this->getHeader('unencoded_url')))
        {
            $this->setUri(new Uri($this->getHeader('unencoded_url')));
        }
        else
        {
            $this->setUri(new Uri($this->getHeader('request-uri')));
        }
```

If you prefer, the other option is to add in the file read.me a warning for those who use urls with characters utf8 add this hack before calling `router()->start()`:

	if ( isset($_SERVER['UNENCODED_URL']) ) 
	{
		$_SERVER['REQUEST_URI'] = $_SERVER['UNENCODED_URL'];
	}

Thank you for your hard work on solving this issue.

**Comment by jatubio** [comment]
Tested also on 3.4.1. It's works, but I need too add '%' character to my regex.

**Comment by skipperbent** [comment]
@jatubio Thanks for the update.

Ahhh of course! Great you finally got it working! The __construct values are overwritten when running unit tests because `REQUEST_URI` isn't available from the console - you specify which url you want to "simulate", the `TestRouter::debugNoReset('/test/Dermatología');` basicly just calls `request()->setUri()` and starts the routing.

Did you get it working on 3.4.1 without the `unencoded_url` header modification or do we still need to implement that in the constructor of `Request`?

Thanks for your works, I'm glad it's finally working properly :)

**Comment by jatubio** [comment]
Yes, that step is necessary.
At first I left that part out of the builder code. Because I thought it best that the responsibility to decode the parameters is from the external classes.

But, after your question, I have re-included the code in the constructor and, after several tests, I think it is the best site, since otherwise, the project would behave differently with IIS as it does with other servers .

If you include it in the code, in addition, it is no longer necessary to add '%' to the regex because the parameters will get encoded correctly.

So, this would be the definitive code:

**Comment by jatubio** [comment]
Sorry, I have misread your last comment and think that question was about `urldecode()` instead of `unencoded_url`, hahaha.

On IIS, if url have utf8 or encoded characters, you need to get `unencoded_url` because `request-uri` will have a wrong value. If I don't change this and left only `request-uri`, any route with utf8 characters will match the default route this was what happened here: https://github.com/skipperbent/simple-php-router/issues/268#issuecomment-324458228. But at that moment I did not know what the problem was.

**Comment by skipperbent** [comment]
@jatubio Thanks for the feedback - I really appreciate your help and that we got this working 👍

I've added the additional check for `unencoded_url`, if available that header will be set, otherwise the default `request_uri` header will be used instead.

The fix will be available shortly so you can avoid any hacking in the library, which will just give you headache once you update the library in the future 😆

**Comment by skipperbent** [comment]
Your fix is now included in version 3.4.2 👍 

Thanks for reporting the issue and helping solving it!

/ Simon

**Comment by jatubio** [comment]
Thank you Simon :+1:. I'm glad to help you.

¿Have you thinked about use urldecode over 'encoded_url'? https://github.com/skipperbent/simple-php-router/issues/268#issuecomment-324489672

I'm not sure but, may be, encoded_url on IIS don't returns the same value as request-uri on Apache. And to be 100% compatible you need to urldecode it.

With: `/test/Dermatología`, ¿What's you get from `$this->getHeader('request-uri')`?¿It's `/test/Dermatolog%C3%ADa` or `/test/Dermatología`?

If it's `/test/Dermatología`, you need to apply `urldecode` to `encoded_url` header to make the method 100% compatible with IIS

**Comment by skipperbent** [comment]
I think the `ENCODED_URL` header is IIS specific. Can't find anything in my `$_SERVER` variables; I've tried on both Apache and Nginx. The newly added `Uri` class (version 3.4.0) will automatically try to fix encoding by calling it's `parseUrl` whenever a new instance is created.

The `Uri->parseUrl` method calls `urldecode` on every part of the `parse_url` results (path, query, user etc).

Is version 3.4.2 working with your IIS without any modifications to the code?

**Comment by jatubio** [comment]
Yes, `ENCODED_URL` is IIS specific. This is why I have asked you about debug your code and see what's the value of `$this->getHeader('request-uri')` on Apache and Ngix. Because you can't check 'encoded_url' for IIS and I can't check 'request-uri' for Apache. But we can put both here an compare to find the most compatible method to work with tem.

With 3.4.2 I'm having this error: `Route not found: "/cursos/listado/especialidad/Dermatolog%C3%ADa/" in \pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 294`. This is because the url is not encoded to "/cursos/listado/especialidad/Dermatología/".

I know how to solve, of course. I can urldecode the Url on BootManager or add '%' to regex and urldecode the parameters. But the question is: ***¿I need to do this also on Apache or only on IIS?¿What's better: Do it myself or let the router do it?***

May be you can also test them including this code on your code: `$_SERVER['UNENCODED_URL']='/test/Dermatolog%C3%ADa'`

**Comment by skipperbent** [comment]
Ahh I see your point. Thanks for clarifying! 

I get the same problem with Apache and Nginx - the `REQUEST_URI` header is urlencoded and is returned as `/cursos/listado/especialidad/Dermatolog%C3%ADa/`.

And i agree with you 100% - the router should handle all url decoding, so I've added `urldecode` to the `Uri` so all urls are decoded properly from now on. The new release will be available shortly.

**Comment by skipperbent** [comment]
The fix is released in version 3.4.3. Hopefully you will get no more problems with url-encoding in this release. I've got my fingers crossed 🤞 😆 

Thanks for helping out on this issue - I really appreciate it.

**Comment by jatubio** [comment]
:laughing: :laughing:

Yeah!! Now it's working like a charm! :thumbsup:

I really appreciate also your work and your dedication to solve this issue and to do better this great library. 

I really enjoyed this conversation and also learned a lot.

See you, take care. :grinning: :grinning:

**Comment by skipperbent** [comment]
Great! I'm happy that we got it working! 

Thanks - no problem, I'm here to help and thanks for using the project.

Same here - take care 😄
