### ISSUE TITLE
Passing variables from Middleware to controller/route

### ISSUE THREAD

**Issue by zaingithub** [skipperbent/simple-php-router#269]
How can i sent variable from middleware to the controller?

**Comment by skipperbent** [comment]
You can set whatever you like on the `Request $request` parameter and fetching them by calling `request() ->myParameter`.

**Comment by skipperbent** [comment]
You can see in the documentation under "middlewares" an example here where a user object is set on the `Request` object from a Middleware 

https://github.com/skipperbent/simple-php-router/blob/master/README.md#example

**Comment by skipperbent** [comment]
Are you still having problems passing variables from your middleware to the controller/route or is it ok to close this issue?
