### ISSUE TITLE
Allow response()->json() to accept JsonSerializable

### ISSUE THREAD

**Issue by adamkelso-rg** [skipperbent/simple-php-router#284]
First off, thanks for SimpleRouter. It's awesome.

Currently, the `json()` method on the Response object requires the `$value` argument to be an array. It would be really useful if it could accept either an array or any object that implements the [JsonSerializable interface](http://php.net/manual/en/class.jsonserializable.php). We want to use it to build simplified Fractal like translators.

Thanks.

**Comment by skipperbent** [comment]
Hi @adamkelso-rg .

Thanks, I'm glad that you find the library useful.

I totally agree with you. The `json()` method should accept the `JsonSerializable` interface. I will make sure that this feature is implemented in all versions and released shortly. I really appreciate your feedback. 

/ Simon

**Comment by skipperbent** [comment]
Hi @adamkelso-rg .

The change is now available in version 1.8.1, 2.6.7 and 3.4.4.

/ Simon

**Comment by adamkelso-rg** [comment]
@skipperbent Rock on!

Thanks.
