### ISSUE TITLE
Where is the basepath setting? and where is the csrf_token function? 

### ISSUE THREAD

**Issue by lordmemed** [skipperbent/simple-php-router#292]
yesterday, i have add this func() for personal use. but i forgot to back it up. so i forgot where to set this function?

how do i make it work if it run from sub-dir?

(dont use the htaccess rewritebase) 

and for the csrf_token,  its mentioned at the docs,  but actually where it is?

**Comment by skipperbent** [comment]
Hi @lordmemed.

The `csrf_token` helper function somehow got lost. It will be added to the `helpers.php`-file in the next release and it looks like this:

```php
/**
 * Get current csrf-token
 * @return string|null
 */
function csrf_token()
{
    $baseVerifier = Router::router()->getCsrfVerifier();
    if ($baseVerifier !== null) {
        return $baseVerifier->getToken();
    }

    return null;
}
```

Haven't tried using the library from a sub-dir myself - but you might get it to work by modifying the `REQUEST_URI` from the `Request` class.

Something like this:
```php
request()->setUri(new Uri( 'my-sub-dir/' . request()->getUri()->getPath()  ));
```

You can see an example in the `project/test/Helpers/TestRouter.php` class which simulates sets the `REQUEST_URI` manually in order to unit-tests to work.

Helpers methods can be found in the `project/helpers.php` file.

Hope it makes sense.

/ Simon

**Comment by lordmemed** [comment]
thanks for the answer.

previously, i add the setBasePath and getBasePath function to SimpleRouter Class.
that work perfectly. but accidentally i replace it with the new update. its my fault.
and now i get this error.

> exception 'Pecee\SimpleRouter\Exceptions\NotFoundHttpException' with message 'Route not found: "/web_cms/"' in \www\web_cms\vendor\Pecee\SimpleRouter\Router.php:301 Stack trace: #0 \www\web_cms\vendor\Pecee\SimpleRouter\SimpleRouter.php(60): Pecee\SimpleRouter\Router->routeRequest() #1 \www\web_cms\vendor\HotCode\Routing\Router.php(32): Pecee\SimpleRouter\SimpleRouter::start() #2 \www\web_cms\index.php(19): HotCode\Routing\Router::start() #3 {main}

what i mean is, if i set Router::get('/',function(){});
it goes to basepath(if any)+'/'.

sorry for many questions :). and poor english.

**Comment by skipperbent** [comment]
No problem :) 

I think an easy fix would be to just add a group around all your routes with your base path.

```Router::group(['prefix' => '/web_cms/'], function() {
// your routes here
});
```

Writing this from my phone so please check the documentation if the code above has errors.

Let me know if it works. 

/ Simon

**Comment by lordmemed** [comment]
haha. i get it.
just add it in SimpleRouter class,

```
protected static $BasePath;

public static function setBasePath($basepath)
    {
        static::$BasePath = $basepath;
    }

public static function match(array $requestMethods, $url, $callback, array $settings = null)
    {
        $url = static::$BasePath . '/' . trim($url, '/');
        $url = static::$BasePath ? rtrim($url, '/') : $url;
        ...
```
that solve it. sorry for disturbing you.

btw, what android app did you use?

**Comment by lordmemed** [comment]
hey, anybody there?
one more question, please. :)

whenever i use a form to POST something, it always return an error 'invalid csrf-token',
i have add session and set hidden text input that store csrftoken, but, how do i really use it?

**Comment by skipperbent** [comment]
@lordmemed 

It's a bad idea to add it directly to the SimpleRouter class as it will get overwritte upon update. I would suggest that you use a group instead or extend the SimpleRouter class and overwrite method/add or own and then use that when generating your routes, for example:

```php
class MyRouter extends SimpleRouter {
    // Your basepath stuff here
}
```
and then using that to add your routes:

```php
MyRouter::get('/', 'MyController@method');
```

In regards to the CSRF problem - check that the `CSRF-TOKEN` cookie is created. It might not be created properly as you are not using a proper path. You can disable the functionality by removing the `Router::csrfVerifier()` call in your routes.php

**Comment by lordmemed** [comment]
@skipperbent 

okay, i got it and i have been move it to my router.

and i has solved the csrf problem.
thanks.

sorry if out-of-topic. but i dont want to open another issues.

my problem here with this now.
the route is, `Router::get('/{url}', 'DefaultController@geturl');`

expected result that, '/got-here' to be works, but it doesn't.
it just works if the url is '/got_here', just with the underscore in it.

what happen here? is my fault or there is the problem with regex?

sincerely, @lordmemed

**Comment by skipperbent** [comment]
@lordmemed I'm glad to hear that you got it working 👍 😄 

You need to add a custom parameter regex as the router only matches the regex `\w` (common web characters) which is enough in 99.9 percent of the time. It's done to be as efficient as possible.

**Example:**

```php
SimpleRouter::get('/path/{parameter}', 'VideoController@home', ['defaultParameterRegex' => '[\w\-]+']);
```

Please refer to the "Custom regex for matching parameters" section in the documentation for more info:
https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

**Comment by lordmemed** [comment]
thank you so much for your help.

i think i will close this issues and need more read on the docs.
because, i was missing that part.

waiting for the next update. :)

**Comment by lordmemed** [comment]
you are so kind and easy going with people asking to you.

not like the original author of pixie. he kick me out of conversations. 

for suggest , would you like to create gitter?  so every users doesn't have to open an issues just for asking little thing. 
it's because i can't delete issues on github.  thats their rules.
