### ISSUE TITLE
Request: Add more info on 'Route or method not allowed'

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#297]
Hello:

Would be great if more info about url will show when a 'Route or method not allowed' is throwed.

Thank you.

**Comment by jatubio** [comment]
I have created a pull request :wink: 

https://github.com/skipperbent/simple-php-router/pull/298

**Comment by skipperbent** [comment]
@jatubio I've merged your changes - they will be available in the next release. Thanks for your contribution, I appreciate both your work and feedback 👍

**Comment by jatubio** [comment]
Thank you Simon 👍
