### ISSUE TITLE
CSFR documentation issue

### ISSUE THREAD

**Issue by PSF1** [skipperbent/simple-php-router#299]
Hi,

Nice library : ))

In the readme documentation don't said how set the CSFR token in a form, and not too the name of the field.

I finded that in src/Pecee/Http/Middleware/BaseCsrfVerifier.php, but it will be better has it in documentation.

Thanks

**Comment by skipperbent** [comment]
Hi @PSF1 .

Thanks for your feedback - I agree with you! The documentation definitely needs to mention how to use the token in forms. I'll make sure that the documentation will be updated in the next upcoming.

/ Simon

**Comment by skipperbent** [comment]
I've added a small preview/example in the documentation which are available in version 3.4.5.3.
