### ISSUE TITLE
Route Parsing issue

### ISSUE THREAD

**Issue by Blair2004** [skipperbent/simple-php-router#313]
Hi i'm facing some problem with the script.
When i'm registering a route like so : 

```php
   Route::get( 'foo/{slug?}/{action?}', function( $slug, $action ) {

    }); 

   // and

   Route::get( 'foo-slug/{slug?}/{action?}', function( $slug, $action ){

   });
```

the first route seem to match to this route :
"http://site.com/foo-slug/bar/do"

And the second route is not triggered.

**Comment by skipperbent** [comment]
Hi @Blair2004 .

First of all thank you very much for using the library.

I'm not able to recreate the issue you are experiencing with unit-tests - they all pass just fine. I also tried to recreate the routes using an empty project on a Apache web-server which also matches the correct routes.

**PhpUnit code used:**
```php
public function testIssue313() {
	TestRouter::get('foo/{slug?}/{action?}', 'DummyController@method1');
	TestRouter::get('foo-slug/{slug?}/{action?}', 'DummyController@method1');

	TestRouter::debugNoReset('/foo-slug/bar/do', 'get');
	$this->assertEquals('/foo-slug/{slug?}/{action?}/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());

	TestRouter::router()->reset();
}
```

To help you solve the issue, I would need some more information about your setup. Please provide me with the following details:

- What version of the library are you using?
- What web-server are you using? (Apache, Nginx, Lighttpd, IIS etc.)
- Which version of PHP are you using?
- Dump of all your routes
- In the matched route, it would help alot if you did a dump of the loaded route. Paste the contents of `var_dump(request()->getLoadedRoute())` from the route which are incorrectly matched.

/ Simon

**Comment by Blair2004** [comment]
Hi, thank you for your reply. Here is the details requested.
- I'm not able to retreive version from "composer.json"
- i'm running on Apache
- 7.0 and 5.6
- That function return NULL

From your test, it seems you're using the same method of DummyController.
The problem is when you're using a dash "-", next to a similar prefix on two route, like this : 

Route::get( 'foo/something', function() {
echo 'Foo runs';
});

Route::get( 'foo-bar/something', function(){
echo 'FooBar Runs';
});

in that case, the first route always run for both unless, the second route is placed before the first one (foo).

**Comment by skipperbent** [comment]
Hi @Blair2004.

The unit-tests doesn't use the response from `DummyController` to anything, it's just a placeholder. It could be a function instead. 

These lines are the important ones in the unit-test. The first line tells the router to simulate the path `/foo-slug/bar/do` as if you were to enter that directly into your browser. The next lines checks that the loaded-route matches the correct one, which is `/foo-slug/{slug?}/{action?}`. 

```php
TestRouter::debugNoReset('/foo-slug/bar/do', 'get');
$this->assertEquals('/foo-slug/{slug?}/{action?}/', TestRouter::router()->getRequest()->getLoadedRoute()->getUrl());
```

The test included both `/foo/{slug?}/{action?}` and `/foo-slug/{slug?}/{action?}`  but for some reason i forgot to paste that into the example in my previous post.

You can find the library version you are using by searching after `pecee/simple-router` in your `composer.lock` file. The version number will be displayed somewhere next to the name. The current release is 3.4.5.6.

Maybe I'm misunderstanding the issue, but no-matter what I've tried, I can't get `/foo-slug/bar/do` to match the `foo/{slug?}/{action?}` route like you 😞 Even the example in your previous post renders the correct route just fine.

In the route that renders first, try adding this line in the beginning and paste the contents here.

```php
die(var_dump(\Pecee\SimpleRouter\SimpleRouter::request()));
```

Alternatively you can try to clone the simple-router demo project. I've added some foo routes you can checkout.

Link:
https://github.com/skipperbent/simple-router-demo

/ Simon

**Comment by skipperbent** [comment]
Are you still experiencing issues with the simple-php-router library?

**Comment by Blair2004** [comment]
Hi, sorry for the delay, i would like to add you to my private repository. You might better understand the issue. Let me know if you're ok with that :)

**Comment by Blair2004** [comment]
I have invited you (To NexoPOS). We'll continue the discussion there. 
Thank you.
