### ISSUE TITLE
response()->json doesn't return correct content type

### ISSUE THREAD

**Issue by sandrodz** [skipperbent/simple-php-router#332]
<img width="366" alt="screen shot 2017-12-06 at 11 07 08 am" src="https://user-images.githubusercontent.com/8479569/33649053-cbb908e8-da75-11e7-93ff-64ce3e2ab594.png">
<img width="680" alt="screen shot 2017-12-06 at 11 07 25 am" src="https://user-images.githubusercontent.com/8479569/33649054-cbd684ea-da75-11e7-84e7-d581ad6e7bf2.png">

**Comment by skipperbent** [comment]
Hi @sandrodz.

The `response()->json()` method automatically will automatically set the content-type to `application/json` unless the `$value` parameter is not a valid `JsonSerializable` instance or `array`.

Using `-I` will only show document-info. To see http-headers please use the `-i` parameter instead which will include response headers (not that intuitive param options haha).

```
curl -i https://donate.girchi.ge/orders
```

/ Simon

**Comment by sandrodz** [comment]
Yep, your right. My bad!
