### ISSUE TITLE
Installing without composer?

### ISSUE THREAD

**Issue by trenyture** [skipperbent/simple-php-router#346]
Is there a way to install your Router without using Composer?
Thanks

**Comment by skipperbent** [comment]
The library doesn't require any dependencies, so you can install it in any project without composer, as long as you get the autoloading working manually - however this should only be used as a last-resort, integrating composer into the project would be highly recommended as it will add great benefits like other third party libraries, easy updating and autoloading.

**Comment by skipperbent** [comment]
Closing this issue - feel free to reopen if you have any further questions.
