### ISSUE TITLE
Routes on paths

### ISSUE THREAD

**Issue by systemEDOM** [skipperbent/simple-php-router#401]
The routes do not work if I have the project for example "localhost/project/public" or "mydomain.com/test"

**Comment by skipperbent** [comment]
Hi @systemEDOM 

Using the library on a sub-path like that is not officially supported yet, however it would be be possible to get it working quite easily.

Remember to change `/local-path` to your own local path (`/project` or `/test`).

## Version 4.1.0.0 or above

Add event that appends your local-environment when running on localhost.

**Example:**

```php
// ... your routes.php file

if($isRunningLocally) {

    $eventHandler = new EventHandler();
    $eventHandler->register(EventHandler::EVENT_ADD_ROUTE, function (EventArgument $arg) use (&$status) {

        if ($arg->route instanceof \Pecee\SimpleRouter\Route\LoadableRoute) {
            $arg->route->prependUrl('/local-path');
        }

    });

    TestRouter::addEventHandler($eventHandler);

}
```

## Other versions

Wrap your routes in a group with a prefix and then changing the prefix depending on your environment (supposing you are only running your project in a sub-path on localhost).

If you don't want the group to fill your `routes.php` you could easily extending the `SimpleRouter` class and add the group in here by extending the `start` method.

**Example:**

```php
class Router extends \Pecee\SimpleRouter\SimpleRouter 
{
    public static function start()
    {
        $prefix = ($isRunningLocally) ? '/local-path' : null;
        
        static::group(['prefix' => $prefix], function() {
                
            // require routes.php
            require_once 'routes.php';
            
        });
        
        parent::start();
    }
}
```

/ Simon

**Comment by skipperbent** [comment]
If you run a sub-path both on live and localhost you should just wrap your routes in a group and change the prefix depending on your environment.

**Comment by systemEDOM** [comment]
Thank you very much i did could fix it. It's cool the routes system

**Comment by skipperbent** [comment]
@systemEDOM 

Cool - I'm glad to hear that you fixed your issue and thanks for using the library 👍
