### ISSUE TITLE
Updating the default regex to support on slug with hyphen or dot

### ISSUE THREAD

**Issue by Blair2004** [skipperbent/simple-php-router#403]
https://github.com/skipperbent/simple-php-router/blob/0fc40f2a82ea19912de1ee255fa5e72cad81fcf4/src/Pecee/SimpleRouter/Route/Route.php#L12

After having reviewed the core, i've noticed that when i add this regex expression : 
```php
protected const PARAMETERS_DEFAULT_REGEX = '[\w|.|-]+';
```
that allow a match of following url `/something/{foo}/{bar}` where `foo` or `bar` can be a sting with hyphen '-' or dot '.' like so : 

`/something/foo-bar/bar-foo`

**Comment by skipperbent** [comment]
Hi @Blair2004 .

Thanks for taking the time to review the code, I really appreciate it.

The `PARAMETERS_DEFAULT_REGEX` const is as sparse as possible to improve the performance and to ensure that the end-user have the full control over how parameters are matched.

If you have routes that contains special parameters, you can easily override the default regular-expression by setting the `defaultParameterRegex` options parameter.

More info here:
https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

/ Simon

**Comment by Blair2004** [comment]
Great... is that new ? i've noticed that.
