### ISSUE TITLE
Posting content-type : 'application/json' 

### ISSUE THREAD

**Issue by mtaylor456** [skipperbent/simple-php-router#413]
PHP 7.2 apache 2.4

Posting 'application/json' content to the router.

`file_get_contents('php://input')` successfully returns the json content

`router::request()->getInputHandler()->all() ` returns an empty array 

The `all()` method only checks this input for  `['put', 'patch', 'delete']`, is this correct?

**Comment by skipperbent** [comment]
Hi @mtaylor456.

Thanks for using the library and reporting the issue.

You're absolutely right, the check is an error.

I've added a new release containing this fix (version 4.2.0.3):
https://github.com/skipperbent/simple-php-router/releases/tag/4.2.0.3

/ Simon

**Comment by mtaylor456** [comment]
Thanks
