### ISSUE TITLE
Issue with php 7.0

### ISSUE THREAD

**Issue by Blair2004** [skipperbent/simple-php-router#414]
Before, the script was compatible with PHP 7.0 and even previous version down to 5.6. But now it seems like the project is only compatible with php 7.1 and greather. That is nto a  bad thing, but i've received a lot of issue submittion on my item description (even refund request). Hope we can find a wayout for this. You have a great tool, that's why so far i'm using it.

Regards.

**Comment by skipperbent** [comment]
Hi @Blair2004.

Unfortunately the latest version of the library has been upgraded to support PHP 7+. The reason for this upgrade is that PHP 5.6 is closely reaching it's EOL and will no longer be supported by January 2019. Third party software like HHVM has already dropped support for PHP 5.6 entirely.

If you need to use the library on PHP versions prior to 7.1, you can use version 3.* and below which is compatible. If you include a php-version to your `composer.json`, composer will only upgrade to versions compatible with your project.

/ Simon
