### ISSUE TITLE
Incorrectly optional character in route

### ISSUE THREAD

**Issue by scottfriebel** [skipperbent/simple-php-router#421]
I have a route using this string to match a url 
`api/v1/users/{userid}/projects/{id}/pages/{pageid?}` 

and that matches either
`/api/v1/users/me/projects/8399421535/pages/43`
or
`/api/v1/users/me/projects/8399421535/pages43`

Is this expected behavior? It doesn't seem that it should match the second url.

**Comment by skipperbent** [comment]
Hi @scottfriebel.

Thanks for taking the time to report the issue. 
The fix has been released and is available in the latest version 4.2.0.4.

Feel free to reopen or create another ticket if you experience any further issues.

/ Simon
