### ISSUE TITLE
SimpleRouter::get('/page/{var}', function ($var) not working correctly

### ISSUE THREAD

**Issue by tafelnl** [skipperbent/simple-php-router#433]
Replicate as following:

add a router like this:
`SimpleRouter::get('/page/{var}', function ($var) `

when you type the following URL it will fail:
`https://domain.com/page/abc-xyz`

It is because of the `-` between `abc` and `xyz`

Because when you type the following URL it will resolve correctly:
`https://domain.com/page/abcxyz`

**Comment by skipperbent** [comment]
Please have a look in the documentation on how to customize the parameters.

https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

```php
SimpleRouter::group(['defaultParameterRegex' => '[\w\-]+'], function() {

    SimpleRouter::get('/path/{parameter}', 'VideoController@home');

});
```

/ Simon

**Comment by tafelnl** [comment]
Sorry, I should have read the documentation better. Thank you very much for your time. I appreciate it :)
