### ISSUE TITLE
CSRF Token NULL

### ISSUE THREAD

**Issue by disiri** [skipperbent/simple-php-router#437]
Hi,

I have a landing page which has a form.
CSRF token seems like getting set after my routes is called. Because of that csrf_token() always throw null on every first load.

Tested on incognito, only happens every first load. (clear your cache every time you test it)

**Comment by rotichbryant** [comment]
Hi disiri,

i too had the same issue. have you found any solution besides from here?

**Comment by skipperbent** [comment]
I will look into this. You could create your own token handler until the issue has been resolved.

**Comment by markezure** [comment]
Hi...


If anyone is still having problems with csrf_token () ... Just remove return null after if and you're done

**Comment by skipperbent** [comment]
This issue will be resolved in upcoming release (version 4.3.0.0).

**Comment by skipperbent** [comment]
This issue has been resolved in version 4.3.0.0.
Feel free to open another issue if you are still experiencing issues.
