### ISSUE TITLE
help me please DI

### ISSUE THREAD

**Issue by DeNIKE666** [skipperbent/simple-php-router#443]
Please help me how can I do something so that I could inject a class in my controller

For example:

public function login (User $ user) {
  return $user->id;
  and I can get the new $ User class;
}

I do not work DI.
I always get an error when I try to add a class in the controller controller.

http://prntscr.com/mctajz

**Comment by Tahrz** [comment]
> Please help me how can I do something so that I could inject a class in my controller
> 
> For example:
> 
> public function login (User $ user) {
> return $user->id;
> and I can get the new $ User class;
> }
> 
> I do not work DI.
> I always get an error when I try to add a class in the controller controller.
> 
> http://prntscr.com/mctajz

Hi! Can you show your class for example? 

About error, you need send one parameter to method `PathDomain()`

**Comment by DeNIKE666** [comment]
I am just passing User $ user, could you help and tell me how to do it right? give your contacts please

**Comment by Tahrz** [comment]
> I am just passing User $ user, could you help and tell me how to do it right? give your contacts please

backer.crown@gmail.com

**Comment by DeNIKE666** [comment]
Ну что не знаете как решить эту проблему?

ср, 30 янв. 2019 г., 16:03 Taras Ziabukhin notifications@github.com:

**Comment by Tahrz** [comment]
> Ну что не знаете как решить эту проблему? ср, 30 янв. 2019 г., 16:03 Taras Ziabukhin notifications@github.com:
> […](#)

Anser on your email

**Comment by Tahrz** [comment]
So, one more time: you have errors, because method login expect a User type object, and you do not give it.

right method call:
```
$user = new User();
login($user)
```

but it will not a normal login.

correct example for call this method, can be:
```
$user = UserRepository:findUserByEmail($request->get('email));
if (login($user)) {
  // some action
}

// else action
```

**Comment by DeNIKE666** [comment]
Спасибо большое, попробую так сделать как вы говорите.

пн, 4 февр. 2019 г. в 16:10, Taras Ziabukhin <notifications@github.com>:
