### ISSUE TITLE
A question about shared hosting Vs. VPS

### ISSUE THREAD

**Issue by lcquadros** [skipperbent/simple-php-router#447]
Hello, Simon and folks;

Can you guys help me with this one? Does Simple-php-router works with wildcard subdomains on shared hosts? It will be good to know beforehand.

I will start soon a project on AWS infrastructure and another on a shared host and that router will be a great resource.

Thanks in advance.

**Comment by skipperbent** [comment]
Hi there.

It works fine as long as you are url- rewriting the server properly. I've used it on several project requiring custom domains, including aliases (where sub.domain.com is an alias for sub2.domain2.com etc - used to hide the long domain for an image host and make it appear part of the sites domain).

I hope this answered your question.

/ Simon

**Comment by lcquadros** [comment]
Yes It did. Good to know how far it can go.
Thank you.
