### ISSUE TITLE
Multi Depth Routing Doesn't Work?

### ISSUE THREAD

**Issue by nicholaspearson** [skipperbent/simple-php-router#451]
`SimpleRouter::get('/legal/terms/', 'LegalController@getTerms')->name('legal.terms');
SimpleRouter::get('/legal/privacy/', 'LegalController@getPrivacy')->name('legal.privacy');`

With a URL of /legal/terms simply doesn't work. But it works on my MAC using the Built in PHP web server (php -S 127.0.0.1:8000).

Also, why does it default to /legal/terms/ and not /legal/terms. It doesn't seem to make sense. Legal is the folder and terms is the page. An additional / would indicate a directory.

**Comment by nicholaspearson** [comment]
I've noticed that PHP_SELF is different on my Linux server compared to my MAC.

OSX:
`"PHP_SELF" => "/index.php/legal/terms/"`

Linux Server:
`"PHP_SELF" => "/index.php"`

That was on the same URL.

Any ideas?

**Comment by nicholaspearson** [comment]
@skipperbent Are you able to advise please?

**Comment by skipperbent** [comment]
What webserver are you using? What version of simple-router are you using? I'm running multiple project on Apache and Nginx on Debian with no problems and I do not have the problem with additional slashes (/) in paths in the latest version.

Please read the debug section of the documentation and post the of your contents simple-router debug-info here.
It contains information about your linux-webserver (like headers, router, rewriting) that can help me resolve the issue.

Thanks.
