### ISSUE TITLE
Question: How to set filterEmptyParams=false?

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#453]
Hello,

I need to set filterEmptyParams of every loaded route to false.

I have my CustomRouter class, and have overloaded addRoute() method, but I can't change filterEmptyParams property because it's protected.

	class CustomRouter extends \Pecee\SimpleRouter\Router
	{
		/**
		 * Add route
		 *
		 * Ponemos filterEmptyParams a false
		 *
		 * @param IRoute $route
		 * @return IRoute
		 */
		public function addRoute(IRoute $route): IRoute
		{
			$route->filterEmptyParams=false;

			return parent::addRoute($route);
		}

Another option is to use my custom `RouteUrl` class, but I don't know how to use my class on match() and all() method without overwrite full method.

 Thanks in advance.

**Comment by skipperbent** [comment]
Hi jatubio.

I've added the option to enable or disable the `filterEmptyParams` parameter on the `IRoute` interface. The changes will be available on the next release (version 4.3).

**Comment by skipperbent** [comment]
This issue has been resolved in version 4.3.0.0.
Feel free to open another issue if you are still experiencing issues.
