### ISSUE TITLE
Passing variable to middleware

### ISSUE THREAD

**Issue by JesseHendriks** [skipperbent/simple-php-router#454]
Hello,

Is there a way to send data to the middleware?

I want to use this for roles/permission.

For example, I want to make some routes that only can be accessed by the administrator. He has the role ADMIN, but I am not sure how I can send this in a route to the middleware I'm using for the check.

Hope you can help!

**Comment by skipperbent** [comment]
Hi.

There's an example in the documentation.

You can easily pass variables by adding the to the request object.

Example:

request()->isAdmin = true.

ons. 24. apr. 2019 12.31 skrev Jesse Hendriks <notifications@github.com>:

**Comment by JesseHendriks** [comment]
Thank you for your response!

I'm aware of that part, but if I want to add permissions per route, for example, can_edit_news (in my database I added the permissions to the user). I have a route something like this: Router::get('/news/{id}/edit', 'News@edit')->addMiddleware(\App\Middleware\Permission::class);

Is there a way to add to this router an option to send the needed permission (can_edit_news) ? I actually want to send it to the Permission middleware class.

**Comment by skipperbent** [comment]
Maybe I'm misunderstanding. I would add all the routes regardless of the
users permission and wrap those that require permission in a group that
uses the Permission middleware.

Within the Permission middleware i would then check if the users has access
to the route by mapping the route to the permission name (/news/{id}/edit
to can_edit_news etc) and then checking if the user has that permission.

If the user does not have access I would then throw a 401 exception within
the middleware and have a custom exception-handler that catches 401 errors
and displays a page with the unauthorized access message.

- Simon

ons. 24. apr. 2019 13.02 skrev Jesse Hendriks <notifications@github.com>:

**Comment by Chubinets** [comment]
В каком месте нужно передать `request()->isAdmin = true`?

**Comment by Ryan-Pell** [comment]
Im having a similar issue with passing though a varable to the middleware. I have differnt permissions to check on each get.

**Comment by skipperbent** [comment]
> Thank you Simon, I know what to do now!

I'm glad you managed to resolve the issue :)

**Comment by xJuvi** [comment]
> Thank you Simon, I know what to do now!

Hi @JesseHendriks 
how did u solve this problem? I can't access the unparsed url in the middleware and can't found a way to get an unique item for ever route.

Kind regards

**Comment by JesseHendriks** [comment]
@xJuvi sorry I'm not using the package anymore (using Laravel now).

**Comment by pietmarcus** [comment]
Maybe I'm late to the party, but I managed to add parameterized middlewares. I created a middleware-class:
`class HasRoleMiddleware implements IMiddleware {
    private $role;
    public function __construct(string $role) {
        $this->role = $role;
    }
    public function handle(Request $request): void {
        // @todo write custom logic
    }
}`

On my group/or route I added the middleware:
`SimpleRouter::group(['middleware' => [new HasRoleMiddleware('adm')]]`....`

**Comment by xJuvi** [comment]
hi @pietmarcus 
in my project i need dynamic roles to use. So i created the PR #604 to pass the current rule name to the middleware, where i select the specific roles from my database.
But for now, i changed the repo to this fork:
https://github.com/DeveloperMarius/simple-php-router/tree/v5-development-php8

There are some fixes for php8 and many other things. The most of open PRs from this project were merged in the forked repo.

Kind regards
