### ISSUE TITLE
Закрепить метод за экшеном

### ISSUE THREAD

**Issue by Chubinets** [skipperbent/simple-php-router#458]
Не знаю почему этого не сделали раньше, может кто то уже это предлагал.
Мое предложение: сделать по умолчанию так чтобы метод закреплялся на экшеном. Например:

> SimpleRouter::get('/', 'HomeController@index'); //HomeController()->getIndex
> SimpleRouter::post('/', 'HomeController@index'); //HomeController()->postIndex
> SimpleRouter::all('/', 'HomeController@index'); //Возможные варианты: HomeController()->getIndex, 
HomeController()->postIndex,HomeController()->putIndex и другие

Или же хотя бы это вынести это под галочку

РЕШЕНИЕ:

https://github.com/skipperbent/simple-php-router/blob/153f8630f2abde6c58bb7109f1f8ebd5d23a53e6/src/Pecee/SimpleRouter/Route/Route.php#L116

ЗАМЕНИТЬ НА: 
> $method = strtolower($_SERVER['REQUEST_METHOD']).ucfirst($controller[1]);

**Comment by tahrz** [comment]
Так в примере же метод из контроллера, и кажется так и должно работать из-под коробки. В случае же с экшинами, расчет именно на `__invoke()` метод

**Comment by KarelWintersky** [comment]
@Chubinets , плохое решение, потому что провоцирует возникновение "механизма по умолчанию", непрозрачного, неочевидного.

```
SimpleRouter::get('/', 'HomeController@form_display_welcome_page');
```
что теперь куда должно закрепиться?

**Comment by Chubinets** [comment]
@KarelWintersky 

class HomeController
{
    public function getFrom_display_welcome_page ()
    {
         //
    }
}

**Comment by KarelWintersky** [comment]
@Chubinets и что это даст? Что даст этот "сахар", который еще к тому же и несладкий. 

Несладкий он в том, что заставляет меня писать методы с другими именами.

Не `HomeController::form_display_welcome_page`, а запоминать неочевидное правило трансляции в 
`getForm_display_welcome_page` (а почему не `get_form_display_welcome_page` ?)

Короче, вам надо - делайте под себя форк под свои хотелки.

**Comment by Chubinets** [comment]
@KarelWintersky хм, каждому свое.
