### ISSUE TITLE
Route  not  found  error

### ISSUE THREAD

**Issue by inicio015** [skipperbent/simple-php-router#459]
Install the library using composer and create an index.php file to test and I made it simple like this:
```
<?php
include_once('vendor/autoload.php');
use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::get('/', function() {
    return 'Hello world';
});

// Start the routing
SimpleRouter::start();
```

But I'm getting the following error
Fatal error: Uncaught Pecee \ SimpleRouter \ Exceptions \ NotFoundHttpException: Route not found: "/ practices / routing /" in C: \ xampp \ htdocs \ practices \ routing \ vendor \ pecee \ simple-router \ src \ Pecee \ SimpleRouter \ Router .php: 430 Stack trace: # 0 C: \ xampp \ htdocs \ practices \ routing \ vendor \ pecee \ simple-router \ src \ Pecee \ SimpleRouter \ Router.php (331): Pecee \ SimpleRouter \ Router-> routeRequest ( ) # 1 C: \ xampp \ htdocs \ practices \ routing \ vendor \ pecee \ simple-router \ src \ Pecee \ SimpleRouter \ SimpleRouter.php (63): Pecee \ SimpleRouter \ Router-> start () # 2 C: \ xampp \ htdocs \ practices \ routing \ index.php (11): Pecee \ SimpleRouter \ SimpleRouter :: start () # 3 {main} thrown in C: \ xampp \ htdocs \ practices \ routing \ vendor \ pecee \ simple-router \ src \ Pecee \ SimpleRouter \ Router.php on line 430

I can not make the router library work and I already included the htaccess file as it is in the help guide please :(

**Comment by tahrz** [comment]
Hi! Have you try to install [demo]( https://github.com/skipperbent/simple-router-demo)?

**Comment by afatoga** [comment]
in demo app, file: CustomExceptionHandler.php

change line 39, to:
$request->setRewriteCallback('Demo\Controllers\DefaultController@notFound');

there was missing a word 'Demo\' in the given path.
