### ISSUE TITLE
Route not found 

### ISSUE THREAD

**Issue by realrecordzLab** [skipperbent/simple-php-router#462]
I want to try this nice routing library to have a complete solution that can sobstitute `FastRoute` in my projects. I've installed it using composer and I've created a simple `routes.php` file where I've this code:
```
<?php

require_once __DIR__.'/vendor/autoload.php';

use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::get('/', function () {
    return ;
});

SimpleRouter::get('/search/{event}', function ($event) {
    return 'Event with id: ' . $event;
});

?>
```
Then I've setted up the `.htaccess` and the `index.php` files in this way: 

**.htaccess**
```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteCond %{SCRIPT_FILENAME} !-l
RewriteRule ^(.*)$ index.php/$1
</IfModule>
```
**index.php**
```
<?php

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/routes.php';

use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::start();
?>
<form method="GET" action="search/" name="">
  <input type="search" name="event" />
  <button type="submit">Cerca</button>
</form>
```

If i call the root of my project It will work and the form is showed, but if I submit the form, I will get this error: 
```
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/search/" in /Users/lab/www/test/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:430 
Stack trace: #0 /Users/lab/www/test/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(331): Pecee\SimpleRouter\Router->routeRequest() #1 /Users/lab/www/test/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(63): Pecee\SimpleRouter\Router->start() 
#2 /Users/lab/www/test/index.php(17): Pecee\SimpleRouter\SimpleRouter::start() 
#3 {main} thrown in /Users/lab/www/test/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 430
```
What I'm doing wrong?
Also I want a pretty url when the form is submitted, so, instead of this `http://localhost:8080/search/?event=bhsim` it will be cool to have this url `http://localhost:8080/search/event/bhsim` is this possible?

**Comment by skipperbent** [comment]
What is the url when the form is submitted? 

I'm assuming your form is a search form that doesn't post?

You need to make your search parameter optional if you want it to work without any search-queries.

```php
SimpleRouter::get('/search/{event?}', function ($event) {
    return 'Event with id: ' . $event;
});
```

Depending on how `event` parameter is formatted, you might want to look into custom parameter regular expressions if you are using special characters.

https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters
