### ISSUE TITLE
Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route "/event/add/" or method "post" not allowed.

### ISSUE THREAD

**Issue by realrecordzLab** [skipperbent/simple-php-router#464]
I get always this response message if I post to a configured route using ajax. What's wrong with my configuration?

```
<?php
//This is the route that will display the page using the plates template engine
SimpleRouter::get('/event/create', 'Controller@eventForm');
//This is the route where ajax will post data, the script is inside the page loaded by the route above 
SimpleRouter::post('/event/add', 'EventsController@addEvent');
?>
```
>Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route "/event/add/" or method "post" not allowed.

The strange thing is that the posted data will be saved inside the database without problems. Another issue I'm having using this library is with the parameters passed using the url. I have this route: 
```
<?php 
SimpleRouter::get('/search/event/{id}', 'EventsController@searchEvent');
?>
```
I need to get the last parameter but the `$_GET` array is empty and i get this error: 
> PHP Notice:  Undefined index: id

Any fix for these two issues?

**Comment by skipperbent** [comment]
Are you still experiencing the issue?

You parameter `id` is not a `$_GET` parameter. It will be passed on to the `searchEvent` method.

**Comment by realrecordzLab** [comment]
Honestly I don't remember,it's passed too much time. I don't have anymore the code of the project where I've used this library, sorry.
