### ISSUE TITLE
setName shows both pages

### ISSUE THREAD

**Issue by devraizer** [skipperbent/simple-php-router#465]
Hey all,

I have a question. When i add setName method in my route for example:

> Router::get('/', 'home\index@index')->setName('index.home');

And after that trying to do a redirect with $request->setRewriteUrl('index.home') i my middleware 

```
class LoggedinMiddleware implements IMiddleware
{
    public function handle(Request $request): void
    {
        if($request->player === null) {
           $request->setRewriteUrl()
        }
    }
}
```

He loads the view 2 times when im i visit the get below

`Router::get('/community/team', 'community\team@index')>addMiddleware(LoggedinMiddleware::class);`

Does anyone know why?

Bryan

**Comment by devraizer** [comment]
Ok thats because he always want a return false

**Comment by skipperbent** [comment]
Hi Bryan.

Did you resolve your issue?

/ Simon

**Comment by skipperbent** [comment]
The next version (4.3) you will be able to disable multi-route rendering by using the `SimpleRouter::enableMultiRouteRendering(false)` - which will enable you not to return any value.
