### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by Zenternal** [skipperbent/simple-php-router#466]
```
[24-Sep-2019 16:13:59 Europe/London] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/staff/mainHome/" in /home/itspowe1/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:430
Stack trace:
#0 /home/itspowe1/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(331): Pecee\SimpleRouter\Router->routeRequest()
#1 /home/itspowe1/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(63): Pecee\SimpleRouter\Router->start()
#2 /home/itspowe1/public_html/staff/index.php(14): Pecee\SimpleRouter\SimpleRouter::start()
#3 {main}
  thrown in /home/itspowe1/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 430

```

I've tried so many routers, and I'm just stuck.
My project is based in a directory called /staff
.
I created a file in staff/_include called routes.php, and in my index.php inside staff/ I put 
```
use Pecee\SimpleRouter\SimpleRouter;
require_once("_include/global.php");
require_once '_include/routes.php';

        SimpleRouter::start();
```

Inside my global.php file is my link to my autoload.

**Comment by tahrz** [comment]
Hi! Can you show `routes.php` file?

**Comment by NGC23** [comment]
Any Updates here? As i am currently using the package for an api implementation and i have a vue js server running on port 8000 on local and then i have my api on port 8080, both local host, but simple router works on all GET requests, but when i post i get the following:`/dashboard/create - Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route "/dashboard/create/" or method "options" not allowed.`

**Comment by skipperbent** [comment]
You can force the router to use any request-type - by using post and setting the `_method` value to whatever request-type you want `_method=PUT` etc.

Otherwise it will be helpful if you posted your `routes.php` a long with the router-debug information (see documentation) as it contains vital information about your server, php-version and headers.

/ Simon
