### ISSUE TITLE
CORS problem, any solution.

### ISSUE THREAD

**Issue by adrianlaraperez88** [skipperbent/simple-php-router#469]
CORS problem, any solution.

**Comment by bmcminn** [comment]
Would be helpful if you provided more context around your issue.

What CORS error are you getting?

What browser are you using?

Are you using cURL, raw XHR, an AJAX library, etc?

A code sample of the route having the issue?

**Comment by slanden** [comment]
I can't say for the OP, but I'm having an issue with CORS as well.

index.php:
```php
<?php
require('../vendor/autoload.php');
require_once('../src/routes.php');
require_once('../src/helper.php');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: *');
use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::error(function($req, $err) {
  SimpleRouter::response()->httpCode($err->getCode())->json([
    message => $err->getCode() == 404 ? 'Not Found' : $err->getMessage()
  ]);
});

SimpleRouter::start();
?>
```

My routes are in a separate `routes.php`. The client still gets a CORS error with the relevant headers set.

After adding a route for the pre-flight `options` request,

```php
SimpleRouter::options('/login', function (){
  return 'options'
});
```
the following `post` request succeeds, but without the `options` route handler it fails with a 403 and a cors error on the client.

**Comment by skipperbent** [comment]
![2021-03-18_02-17-19](https://user-images.githubusercontent.com/634762/111559081-2a522900-8790-11eb-848e-14cf1b23c1fc.png)

I'm having a hard time reproducing the error. When using postman i get the correct results using the example you provided on Apache running on MAMP with PHP 7.4.

You can try to use the debug feature of the simple-router. It can help you to show what headers the server are sending and more details about the routes loaded. You have to enable debugging manually (see the manual).

Simple-router are matching the request by the `request-method` headers sent from the server. You can also force the request-method by using the `_method` payload and using `POST` - this will force simple-router to use whatever request-method you specify.

/ Simon

**Comment by adrianlaraperez88** [comment]
@skipperbent only you reproducing this error if you send a ajax request

**Comment by skipperbent** [comment]
Is it possible to reproduce the error in postman? That will make it a lot easier to debug

**Comment by skipperbent** [comment]
I'm still unable to reproduce it with ajax using Brave / PHP 7.4 / MAMP / Apache running on MacOS.

**Router**

```php
// load composer dependencies
require '../vendor/autoload.php';

require_once('../app/helpers.php');

use Pecee\SimpleRouter\SimpleRouter;

response()->headers([
    'Access-Control-Allow-Origin: *',
    'Access-Control-Allow-Methods: *',
    'Access-Control-Allow-Headers: *',
]);

SimpleRouter::options('/login', function (){
    return 'options';
});

SimpleRouter::error(function($req, $err) {
    SimpleRouter::response()->httpCode($err->getCode())->json([
        'message' => $err->getCode() == 404 ? 'Not Found' : $err->getMessage()
    ]);
});

SimpleRouter::start();
```

**Ajax**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:#000;">
<div id="demo" style="color:#FFF;"></div>
<script>
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            document.getElementById("demo").innerHTML = this.responseText;
        }
    };
    xhttp.open("OPTIONS", "/login", true);
    xhttp.send();
</script>
</body>
</html>
```

![2021-03-18_04-04-39](https://user-images.githubusercontent.com/634762/111567509-6345ca00-879f-11eb-8c0b-1608e7e59e0e.png)

**Comment by adrianlaraperez88** [comment]
@skipperbent  simple-php-router and ajax call is in same IP/Server if is yes no give to you this error because have same IP, need different IP, and ty for the help

**Comment by skipperbent** [comment]
> @skipperbent simple-php-router and ajax call is in same IP/Server if is yes no give to you this error because have same IP, need different IP, and ty for the help

The test above is on the same IP. I think different IP's might trigger some crossdomain policy ajax restrictions. Back in the good old flash days you had to add a crossdomain.xml policy file on the host site to allow remote request. But there might be some workarounds now-adays, like jsonp:

>The advent of JSONP — essentially a consensual cross-site scripting hack — has opened the door to powerful mashups of content. Many prominent sites provide JSONP services, allowing you access to their content via a predefined API. A particularly great source of JSONP-formatted data is the Yahoo! Query Language, which we'll use in the following example to fetch news about cats.

https://learn.jquery.com/ajax/working-with-jsonp/

**Comment by skipperbent** [comment]
Please see if the new version 4.3.0.0 resolves your issue.

**Comment by AtefR** [comment]
> 

nope, it doesn't

**Comment by cdanielzt** [comment]
I have this issue, any solution?

**Comment by skipperbent** [comment]
> I have this issue, any solution?

It should all be handled by settings the correct headers? Cross browser verifications happens between the browser (client) and the server as far as I'm aware.

```php
response()->headers([
   'Access-Control-Allow-Origin: *',
   'Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS',
   'Access-Control-Allow-Headers: X-Requested-With,Authorization,Content-Type',
   'Access-Control-Max-Age: 86400'
]);
```

If you believe it's an issue with the library, i will need more to go on.
