### ISSUE TITLE
I've tried so many routers, and I'm just stuck.

### ISSUE THREAD

**Issue by OfficialOzioma** [skipperbent/simple-php-router#470]
**

`Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/Startup_structure/" in /opt/lampp/htdocs/Startup_structure/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:430 Stack trace: #0 /opt/lampp/htdocs/Startup_structure/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(331): Pecee\SimpleRouter\Router->routeRequest() #1 /opt/lampp/htdocs/Startup_structure/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(63): Pecee\SimpleRouter\Router->start() #2 /opt/lampp/htdocs/Startup_structure/index.php(11): Pecee\SimpleRouter\SimpleRouter::start() #3 {main} thrown in /opt/lampp/htdocs/Startup_structure/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 430`

**

**Comment by adrianlaraperez88** [comment]
Hi you try call no existing endpoint can you please put your api routes and call

**Comment by OfficialOzioma** [comment]
please show me an example of how to do this

**Comment by adrianlaraperez88** [comment]
Check in the doc the Author have demo is so good for start

**Comment by OfficialOzioma** [comment]
i think the code itself has a bug

**Comment by adrianlaraperez88** [comment]
Can you please give me route code for check what happened ?

**Comment by OfficialOzioma** [comment]
> @adrianlaraperez88 

this the route code

`<?php

use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::start();

SimpleRouter::get('/foo', function() {
    return 'foo';
});

SimpleRouter::get('/foo-bar', function() {
    return 'foo-bar';
});
`

**Comment by OfficialOzioma** [comment]
### @adrianlaraperez88 and this the error am getting

Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/payroll/foo/" in /opt/lampp/htdocs/payroll/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:430 Stack trace: #0 /opt/lampp/htdocs/payroll/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(331): Pecee\SimpleRouter\Router->routeRequest() #1 /opt/lampp/htdocs/payroll/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(63): Pecee\SimpleRouter\Router->start() #2 /opt/lampp/htdocs/payroll/route/web.php(5): Pecee\SimpleRouter\SimpleRouter::start() #3 /opt/lampp/htdocs/payroll/index.php(4): require('/opt/lampp/htdo...') #4 {main} thrown in /opt/lampp/htdocs/payroll/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 430

**Comment by skipperbent** [comment]
Read the readme and download this project. Your routes won't work if they have special characters (_ etc) without a custom regex (see manual).

https://github.com/skipperbent/simple-router-demo
