### ISSUE TITLE
All helper functions MUST be inside namespace

### ISSUE THREAD

**Issue by KarelWintersky** [skipperbent/simple-php-router#472]
... and must be used as

```
use function Pecee\SimpleRouter\Helpers\input as foobar;
```
Otherwise name conflict is possible.

Without this I can't get access to this helper function inside my namespace.

**Comment by skipperbent** [comment]
Hi.

Thanks for your feedback.

The `helpers.php` was originally intended to be optional and copied into whatever project you were using. It's rarely changed and when changes occur it will be specified in the changelog for the release.

I can add it to the library as part of the namespace if that makes it easier to manage within Twig?

/ Simon

**Comment by KarelWintersky** [comment]
What do you wish for? 
No responce needed. Just do it.

**Comment by skipperbent** [comment]
Why not create the class in your project like it was intended?

**Comment by KarelWintersky** [comment]
Because now your helper functions are in global namespace. 

So, your `function redirect()` can broke other code (duplicate declaration, etc)

**Comment by skipperbent** [comment]
The `helpers.php` is not included by composer in the autoload. It's included in the root of the project and not part of the package. If you have issues with `redirect` duplicate, please check that you haven't required the `helpers.php` and create your own version for your specific project.

**Comment by KarelWintersky** [comment]
ok.
