### ISSUE TITLE
500 error's if too many 'slash' characters in url

### ISSUE THREAD

**Issue by brandy** [skipperbent/simple-php-router#473]
I have an issue with the Router and was wondering if anyone has had a similar issue or have any idea how to solve this.

I have a route for my homepage as so:
```
Router::get('/', '\App\Controllers\PageController@home')->setName('home');
```

However If I go to the url `http://site.test//`, I get a 500 error page in Chrome.

Now the same this happens if i have a route for `about`, and do `http://site.test/about//` or `http://site.test//about//`, I will get a 500  error page in Chrome as well.

**Comment by skipperbent** [comment]
Error 500 is just an indication that something went wrong from the webserver. You have to enable php-errors or view the log to find the actual error.

Multiple slashes works perfectly in my tests (they're stripped and by the router) in the latest version of the router. Can't say for the older versions though.
