### ISSUE TITLE
Route Not Found on groups

### ISSUE THREAD

**Issue by REOLDEV** [skipperbent/simple-php-router#475]
Hey there, i have a big problem..
When i have an 404 Error.. for example when i try to call "http://ucp.vicecity-life.local/fraktion/lol"
i get at the end of the page this error... the 404 page is still displayed o.O

`<b>Fatal error</b>:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: &quot;/fraktion/lol/&quot; in E:\DEVSERVER\vhosts\ucp.vicecity-life.local\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php:430
--
  | Stack trace:
  | #0 E:\DEVSERVER\vhosts\ucp.vicecity-life.local\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php(331): Pecee\SimpleRouter\Router-&gt;routeRequest()
  | #1 E:\DEVSERVER\vhosts\ucp.vicecity-life.local\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php(63): Pecee\SimpleRouter\Router-&gt;start()
  | #2 E:\DEVSERVER\vhosts\ucp.vicecity-life.local\index.php(336): Pecee\SimpleRouter\SimpleRouter::start()
  | #3 {main}
  | thrown in <b>E:\DEVSERVER\vhosts\ucp.vicecity-life.local\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php</b> on line <b>430</b><br />`

This is my routes.php

```php
<?php
use Pecee\SimpleRouter\SimpleRouter as router;

//Call Panel Dashboard
router::get('/', function () {
   dashboard();
});

//Faction Group
router::group(['prefix' => '/fraktion'], function () {

    //Dashboard
    router::get('/', function() {
        error_404();
    });

    //Dashboard
    router::get('/dashboard', function() {
        error_404();
    });

    //Member List
    router::get('/mitglieder', function () {
        error_404();
    });

    //Faction Cars
    router::get('/fahrzeuge', function () {
        error_404();
    });

    //Faction Bank
    router::get('/kasse', function () {
        error_404();
    });
});

//404
router::error(function ()  {
   error_404();
});
```

I hope someone can help me with that >.<

**Comment by skipperbent** [comment]
Try this

```php
//404
router::error(function ()  {
   return error_404();
});
```
