### ISSUE TITLE
how send a url as parameter ?

### ISSUE THREAD

**Issue by Misaghahmadi97** [skipperbent/simple-php-router#476]
Hello
I want to send url as parameter but get Error .
url like example.com . any solution ?

**Comment by adrianlaraperez88** [comment]
Hi @Misaghahmadi97, you have 2 options:

`
if( $params && $verb == 'GET' ){
	$url .= '?' . http_build_query($params);
}
`
and another params is part of the route.

**Comment by skipperbent** [comment]
You have to add a custom regular expression if you want to sent special parameters that contains characters than doesn't match `[\w]+` (`a-z`, `A-Z`, `0-9` and `-`). Next version (4.3.0.0 will support `-` too by default).

https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters
