### ISSUE TITLE
Problem with data sended before headers

### ISSUE THREAD

**Issue by danielsanleo** [skipperbent/simple-php-router#478]
I'm having a tedious problem that I don't know how to solve. I think it's clear that it comes from simple-router programming.

`Version: 4.2.0.6`

I explain. My need is to send the client an image. This image must be pretreated by a controller in order to determine if the user has permission. Well, if I want to send the image from the controller as I show in this code:

```
Router::get('/file/{context}/{id}', function ($context, $id) {

	$file = new File($context, $id);

	if ( $file -> CheckFile() ) {

		header("Content-Type: {$file -> type}");
		readfile($file -> path);
		}
	else {
		echo "<h3>Access Denied</h3>";
		}
	}) -> name('file');
```

The resulting image in the user's browser has several characters, which should not appear (The first two characters are 0x0a and 0xff). Among them we have a line break. I know that the first impression may be to think that in the 'File' class there is the problem, I will have left some line break, but it is not so. 100% insurance. Here you have it:

```
<?php
namespace Gestilab\Controllers;

use Gestilab\Helpers;
use Gestilab\Config;
use Gestilab\Logger;

class File extends Helpers {
	# Clase que administra los ficheros y el acceso a ellos
	public $db;
	public $conf;

	public $path;
	public $type;

	public $context;
	public $id;

    function __construct($context, $id) {
		global $db;

		$this -> db = $db;
		$this -> conf = (new Config()) -> getSettings();

		$this -> log = new Logger();

		$this -> context = $context;
		$this -> id = $id;
		}

    public function getFileType() {
		return finfo_file(finfo_open(FILEINFO_MIME), $this -> path);
		}

    public function getFileTypeByExt() {
		$this -> type = pathinfo($this -> path, PATHINFO_EXTENSION);

		return $this -> type;
		}

    public function CheckFile() {
		$this -> log -> write("Comprobando acceso al fichero en contexto de '{$this -> context}' con id: {$this -> id}");

		switch ($this -> context) {
			case 'imagen_firma':

				# Comprobacion permisos del usuario

				# Consultamos existencia del fichero en BBDD
				$sth = $this -> db -> prepare("SELECT imagen_firma
											   FROM usuarios
											   WHERE id=:id");

				$sth -> execute(['id' => $this -> id]);

				$file = $sth -> fetch();

				$this -> path = realpath("{$_SERVER['DOCUMENT_ROOT']}/docs/{$this -> conf['name']}/usuario/{$file['imagen_firma']}");

				break;
			}

		# Comprobamosm que existe, es un fichero y SE TIENE PERMISO
		if (file_exists($this -> path) && is_file($this -> path)) {

			# Comprobamos que tipo de fichero (MIME)
			$finfo = finfo_open(FILEINFO_MIME_TYPE);
			$this -> type = finfo_file($finfo, $this -> path);
			finfo_close($finfo);

			return True;
			}
		else {
			$this -> log -> write("Error, la ruta no existe o es un directorio");
			echo "Error";

			exit;
			}
		}
	}
?>
```

Here comes the funny thing. If I in the definition of the route, to do the test, I put this directly:

```
Router::get('/file/{context}/{id}', function ($context, $id) {

	header("Content-Type: image/gif");
	readfile("/srv/http/nuevogestilab/public/docs/trabajo/usuario/1580299505.gif");

	}) -> name('file');
```

The image comes out perfectly in the browser without any strange character at the beginning.

Then the question is.
Why do strange characters appear when loading a class?

This problem does not only occur when images are sent. I have been able to verify that in the rest of the application it also happens with the HTML result, which rules out that it is a problem of the 'File' class, the difference is that in the rest of the application it does not bother me because it does not influence the result final.

To which I humbly can think that something happens in the simple-router code, which is no longer how to find the problem and correct it.

If you need more information, I give you what you need. I need to solve this problem without bungling.

**Comment by skipperbent** [comment]
In your routes try added return statement at the end like so.

```php
 return readfile("/srv/http/nuevogestilab/public/docs/trabajo/usuario/1580299505.gif");
```

If that doesn't help and reading a file with php works, i would start to uncomment lines in your File class to ensure that nothing is disturbing the output.
