### ISSUE TITLE
Передача параметров в middleware из вне

### ISSUE THREAD

**Issue by Chubinets** [skipperbent/simple-php-router#480]
Мне не очень понравился вариант из коробки, по этому держите мой

1. Заменить функцию **loadMiddleware()**
https://gist.github.com/Chubinets/ec6d98bb974d66639860d68ec6b090fc

2. Создаем файл посредника **middlewares\Access.php**
https://gist.github.com/Chubinets/02a9cbd3cd3f0c3be43bfd3d0a336de8

3. Пример использования
https://gist.github.com/Chubinets/c4935fdd5afb23cf4fffe1aebbacdc0d

Строка разбивается на части разделителем `:`
Первый параметр это название класса, а все последующие параметры, которые передаются в `handle($param1, $param2)`

**Comment by tahrz** [comment]
Лучше закинь пул реквест - хотя автор давненько не заглядывал сюда...

**Comment by skipperbent** [comment]
Please keep the issues in english otherwise I can't help you.
