### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by romather** [skipperbent/simple-php-router#482]
![image](https://user-images.githubusercontent.com/47756883/78465247-67312700-76c9-11ea-9874-acc5bc2ed061.png)

Updating package have some warnings about package jeremeamia/superclosure

**Comment by danalmeida** [comment]
[jeremeamia/superclosure](https://github.com/jeremeamia/super_closure) is a dependency of [PHP-DI](https://github.com/PHP-DI/PHP-DI). See [PHP-DI #711](https://github.com/PHP-DI/PHP-DI/issues/711).

**Comment by romather** [comment]
Closing this question! Thanks for attention !!!
