### ISSUE TITLE
Prefix problem in post method

### ISSUE THREAD

**Issue by novayadi85** [skipperbent/simple-php-router#483]
Hi ,

I am trying use prefix but when post data with ajax, its always switch as get method. 
Any trick to solve my problem?

**Comment by DeveloperMarius** [comment]
Hello,

can you share your routes.php or the affected get and post route?

~ Marius

**Comment by skipperbent** [comment]
Please share you ajax code. Try posting your ajax-code and add `print_r($_SERVER)` in your route and post the contents here. The server variable will have information from the webserver about the request-method.
