### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SimpleRouter' not found

### ISSUE THREAD

**Issue by makkanimation** [skipperbent/simple-php-router#484]
I am getting above issue when i include your package inside index.php
Here is the code which i use:

```
 require_once(__DIR__."/vendor/autoload.php");
    use \Pecee\SimpleRouter\SimpleRouter;
    /* Load external routes file */
    require_once(__DIR__."/routes/routes.php");

    /**
     * The default namespace for route-callbacks, so we don't have to specify it each time.
     * Can be overwritten by using the namespace config option on your routes.
    */

    SimpleRouter::setDefaultNamespace('\Demo\Controllers');

    // Start the routing
    SimpleRouter::start();
```
It always giving me 500 error mentioning :

*Fatal error: Uncaught Error: Class 'SimpleRouter' not found in /var/www/html/.rest/kl/routes/routes.php:2 Stack trace: #0 /var/www/html/.rest/kl/index.php(7): require_once() #1 {main} thrown in /var/www/html/.rest/kl/routes/routes.php on line 2*

**Comment by tahrz** [comment]
Hi! Can you show your **routes.php**?

**Comment by akwatra** [comment]
Hi, @tahrz 
I had the same issue, I got it resolved. 
use below as routes.php  Or use the "use Pecee\SimpleRouter\SimpleRouter;" in top of your routes.php file, it will work. 

file: routes.php
```
<?php
use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::get('/', function() {
    return 'Hello world';
});


SimpleRouter::get('/user/{id}', function ($userId) {
    return 'User with id: ' . $userId;
});

?>
```


**Usage of this inside sub-directory or folder:**
If you are using this as under a sub-directory or folder then you will have to put your sub-folder name prefix with route, ex: 

```
SimpleRouter::get('/sub-folder/', function() {
    return 'Hello world';
});


SimpleRouter::get('/sub-folder/user/{id}', function ($userId) {
    return 'User with id: ' . $userId;
});

```
Hope this helps. :-)

**Comment by skipperbent** [comment]
Hi makkanimation.

Are you still experiencing issues with the project?
