### ISSUE TITLE
404 error route not found

### ISSUE THREAD

**Issue by greentaxi-com** [skipperbent/simple-php-router#489]
This is my page:

require dirname(__DIR__, 1) . "/vendor/autoload.php";
use GT\Core\Init;
use GT\Core\Helper;
use Pecee\SimpleRouter\SimpleRouter as Router;
use Pecee\Http\Url;
use Pecee\Http\Response;
use Pecee\Http\Request;

Init::displayErrors();
Router::start();

Router::get('/', function() {
    return 'Home';
});

Router::get('/search', function() {
    return 'Search';
});

Router::get('/404', function() {
    return '404';
});

Router::error(function(Request $request, \Exception $exception) {
    if($exception instanceof NotFoundHttpException && $exception->getCode() === 404) {
        return '404';
    }
});

Whenever I go to a page which doesn't exist I get the following error. I am unsure why the 404 response is not shown?

Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/error/"

**Comment by parkerj** [comment]
That is because based on your code above, you don't have an `/error/` route defined. On the other hand, based on your `404` route that __is__ registered, according to the example in the readme, something like this should work:
```php
Router::error(function (Request $request, \Exception $exception) {
    if ($exception instanceof NotFoundHttpException && $exception->getCode() === 404) {
        response()->redirect('/404');
    }
});
```
The above code should redirect you to your `/404` route.

**Comment by skipperbent** [comment]
Do you get the same error when dying directly in the error handler?

```php
Router::error(function (Request $request, \Exception $exception) {
    die("it's working");
});
```

**Comment by greentaxi-com** [comment]
Yes I got this working within an error function. Thanks.

**Comment by skipperbent** [comment]
I'm glad you got it working. Thank you too sir and have a nice day!
