### ISSUE TITLE
input find method has different output with normal global methods!

### ISSUE THREAD

**Issue by mmdm95** [skipperbent/simple-php-router#490]
Hi, thanks for this nice library.

### Issue

There is an issue with `find` method inside of `inputHandler` class.
If use `value` (internally it uses `find` method) or `find` method directly, it returns `NULL` on some values but if use global methods directly like `$_GET['file']` or `all` method from `inputHandler` class, it returns correct value.

**The value is not an empty string**

### Example of usage

```php
$file = input('file', 'default value', 'post', 'get');

// return default value !

//===================

$file = input()->all()['file'] ?? 'default value';

// return the value
```

**Comment by skipperbent** [comment]
Hi mmdm95.

Can you provide an example of a value that aren't found when using the `input` helper? Or does this issue you are experiencing apply to all values? Do you get the value if you don't specify a request-type?

Thanks.

/ Simon

**Comment by mmdm95** [comment]
Hi Simon, thanks for reply.

I changed some codes inside library but I think the issue is like this:

- I test it in a simple form submit with following code and results are:

**Method is POST here**

```php
// if the_key is set, it'll be the_value otherwise null
$_POST['the_key'] ?? null;

// if the_key is set or not, the_value will be null
input()->find('the_key');

// if the_key is set, it'll be the_value otherwise null 
input()->find('the_key', 'get', 'post');

// if the_key is set, it'll be the_value otherwise null
input()->all()['the_key'];
```

- I test it in ajax

**Method is POST**

`If method is post, results will be same as simple form submit.`

**Method is GET**

```php
// if the_key is set, it'll be the_value otherwise null
$_POST['the_key'] ?? null;

// if the_key is set, it'll be the_value otherwise null
input()->find('the_key');

// if the_key is set or not, the_value will be null
input()->find('the_key', 'get', 'post');

// if the_key is set, it'll be the_value otherwise null
input()->all()['the_key'];
```

I did not test it on `file` but I think it must be something here not acting as normal behavior

Thanks for your attention

**Comment by skipperbent** [comment]
Try and see if the upcoming version 4.3 has fixed your issues. There was some issues with header parsing - especially the `request-type` header, that might have caused some input-fields not to be populated correctly when using ajax in certain circumstances.

/ Simon
