### ISSUE TITLE
Route not working with (Persian || Arabic) parameters

### ISSUE THREAD

**Issue by Malekfar** [skipperbent/simple-php-router#493]
I have a problem with Persian or Arabic parameters in route.

That is my route:
Route::get('/foo/{name}', function($name) {
   return $name;
});

That is My URL in browser:
http://mysite.dev/foo/نام

And browser shows :
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/foo/%D9%86%D8%A7%D9%85/"

**Comment by skipperbent** [comment]
Wrap your routes in a group that uses custom regex that matches your language.

```php
SimpleRouter::group(['defaultParameterRegex' => '[\w\-]+'], function() {

    SimpleRouter::get('/path/{parameter}', 'VideoController@home');

});
```
