### ISSUE TITLE
Start of string and end of string dont match the route

### ISSUE THREAD

**Issue by miko1991** [skipperbent/simple-php-router#503]
Hello,
I have a /admin route that loads a view that has react in it. So the routes can be like /admin/asd/bec/123 and so on. I used regex

@^\/admin\/?(.*)@i

but that doesnt match the route. What am i doing wrong?

**Comment by skipperbent** [comment]
Try escaping the forward slash

`/^\/admin\/?(.*)/i`

https://regex101.com/r/grS7El/1

**Comment by miko1991** [comment]
> Try escaping the forward slash
> 
> `/^\/admin\/?(.*)/i`
> 
> https://regex101.com/r/grS7El/1

its not why. its because the LoadedRoute looks at the host url AND the request uri. can you change it so that it only looks at request uri? why does it look at host url at all???

**Comment by skipperbent** [comment]
It needs to look at the host-uri in order to determine if the correct host is used. You can setup the routes so it only matches on specific domains. However in your case it will just pass the test.

*Sample below passes and returns `match` as intended *

```php
public function testCustomRegex()
{
    TestRouter::get('/admin/', function() {
        return 'match';
    })->setMatch('/^\/admin\/?(.*)/i');

    $output = TestRouter::debugOutput('/admin/asd/bec/123', 'get');
    $this->assertEquals('match', $output);
}
```

Please provide your `routes.php` if you need additional help.

**Comment by miko1991** [comment]
doesnt work for me. my code

```
        SimpleRouter::setDefaultNamespace("\\Controllers");

        //require_once BASE_PATH."/simpleRoutes.php";

        SimpleRouter::get('/admin/', function() {
            return 'match';
        })->setMatch('/^\/admin\/?(.*)/i');

        SimpleRouter::start();
```

**Comment by miko1991** [comment]
Route not found: "/admin/"

**Comment by miko1991** [comment]
Loadable route does the following
```
return ((bool)preg_match($this->regex, $request->getHost() . $url) !== false);
```
It matches the pattern against the host + url. so the ^ will always fail, because the string matched doesnt start with /admin/. change this please

**Comment by miko1991** [comment]
```

    public function matchRegex(Request $request, $url): ?bool
    {
        /* Match on custom defined regular expression */

        if ($this->regex === null) {
            return null;
        }

        return ((bool)preg_match($this->regex, $url) !== false);
    }
```
please update the package with the following code, it matches.

**Comment by skipperbent** [comment]
Hi Miko.

You're right, I'm sorry - seems like it only applies to custom regular expressions. The default regex handler doesn't even use the `host` either as that check is done elsewhere.

Seems like the reason the test succeeded was that no hostname was defined.

I've changed the code as you suggested and added hostname to the `TestRouter`.

**Comment by miko1991** [comment]
cool thanks :)

**Comment by miko1991** [comment]
please update the package for composer as well

**Comment by skipperbent** [comment]
> please update the package for composer as well

The changes will be available on composer upon release of version 4.3.

**Comment by miko1991** [comment]
cool, when will that be ca?

**Comment by skipperbent** [comment]
Very soon. Within the next week - maybe before, however it depends on the issues. It takes time to sort through them, as most of them are people that don't want to read the documentation or have very bad description which makes it hard to even know if it's an issue or just user error. But I'm working as hard as I can to make everyone happy - you can follow the changes in the Version 4.3 pull-request.
