### ISSUE TITLE
What do you think about a maintenance mode?

### ISSUE THREAD

**Issue by DeveloperMarius** [skipperbent/simple-php-router#506]
Hey,

I asked myself what do you think about some sort of maintenance mode that blocks all requests and just returns a specified html/controller-method/callable.
Just people who are on the IP whitelist can use the router normal.

~Marius

**Comment by skipperbent** [comment]
Would be nice if you could specify some more rules on a group like ip adresses for restricted access.

**Comment by DeveloperMarius** [comment]
True, that in general is a great idea. Also you could specify a browser to block IE for example^^
Can I look more into it and then create a pull request so we can discuss this a bit deeper?

**Comment by skipperbent** [comment]
Sure, go for it 👍  

If you know how to setup php-units for GitHub so that pull-requests are automatically tested I would be grateful if you could help me with that. I've done it on my other projects like `pecee/pixie`, but can't remember how I did it 😄

**Comment by DeveloperMarius** [comment]
👍🏻 
I think you mean GitHub actions? I have never worked with them, but I can look into it^^
