### ISSUE TITLE
Deprecated: call_user_func_array() expects parameter 1 to be a valid callback, non-static method

### ISSUE THREAD

**Issue by Carsak** [skipperbent/simple-php-router#538]
I ve tried add simple route:

`SimpleRouter::post('/todo/add/', [\App\Controller\TodoController::class, 'add']);`

But have this deprecated message:
`Deprecated: call_user_func_array() expects parameter 1 to be a valid callback, non-static method App\Controller\TodoController::add() should not be called statically in`

My controller:

```
<?php
namespace App\Controller;

class TodoController
{
    public function add()
    {
        return 'Add function called';
    }
}
```
PHP version: 7.4.16
Nginx 1.19.10

Is it normal?

**Comment by skipperbent** [comment]
Which version of the router are you using? Please check that you are using the latest version.

/ Simon

**Comment by Carsak** [comment]
> Which version of the router are you using? Please check that you are using the latest version.
> 
> / Simon

I use "pecee/simple-router": "4.3.2.1" version

**Comment by skipperbent** [comment]
Does it work when you use 'TodoController@add' in your route?

**Comment by Carsak** [comment]
> Does it work when you use 'TodoController@add' in your route?

Yes, routing working properly. If I go to url [localhost/todo/add](url) I see 
`Add function called` text

**Comment by skipperbent** [comment]
Strange.. Do you get the same error when using "Controller@Method" and do you get the same error on all routes?

**Comment by skipperbent** [comment]
For example

```php
SimpleRouter::post('/todo/add/', 'TodoController@add');
```

**Comment by Carsak** [comment]
> For example
> 
> ```
> SimpleRouter::post('/todo/add/', 'TodoController@add');
> ```

I will try to test later. At this moment I have not opportunity to test

**Comment by skipperbent** [comment]
Please do, if you don't get the same error it could be a issue with the class hinting. I will do some testing myself and let you know if I find the cause.

Thanks for reporting the issue :)

**Comment by DeveloperMarius** [comment]
Hey,
Thats realy strange.
I tested the following case:
```
public function testClassHint2()
    {
        TestRouter::post('/todo/add/', [DummyController::class, 'method3']);

        $output = TestRouter::debugOutput('/todo/add/', 'post');

        $this->assertEquals('method3', $output);
    }
```
and I get no error using PHP 7.4.6.
Can you try to switch to the lastest PHP 7.4.6 and try it again? I think it have something to do with that.

~ Marius

**Comment by DeveloperMarius** [comment]
Sry,
my fault, yours is the latest. I will try using you version.

**Comment by DeveloperMarius** [comment]
Hey,
yes, I can reproduce this error and it is not only with Class Hint but with every route. I will look more into it.

~ Marius

**Comment by skipperbent** [comment]
Nice to see you @DeveloperMarius!

There was a problem with the class hint after our php 8+ `call_user_func_array` changes. The class was never initiated, but called directly.

I will release a fix shortly.

**Comment by DeveloperMarius** [comment]
Ah, nice. Didn't know that the array of class instance and method is a callable.
Good work!

**Comment by skipperbent** [comment]
> Ah, nice. Didn't know that the array of class instance and method is a callable.
> Good work!

Yeah, It's kinda weird to be honest 😄

**Comment by DeveloperMarius** [comment]
When you look at it again, now it is clear to me. `call_user_func_array` requires a callable and we provide in `loadClassMethod` an array of class and method. So it have to be a callable. But yes, weird^^

**Comment by DeveloperMarius** [comment]
@Carsak version [4.3.2.3](https://github.com/skipperbent/simple-php-router/releases/tag/4.3.2.3) fixes the error. Again thank you for reporting this issue.

~ Marius

**Comment by skipperbent** [comment]
`route.php` line 76 is especially weird. At this point the `$callback` is an array `['class::name', 'methodName']` - yet still is passes the `is_callable` check.

```php
if (is_callable($callback) === true) {
```

@Carsak The issue has been resolved in version 4.3.2.3.

**Comment by DeveloperMarius** [comment]
It's kind of an aggressive to change this behaviour in PHP 7.4.
All my tests returned true:
```
$callback = [new DummyController(), 'method1'];
var_dump(is_callable($callback) === true);

$callback = [DummyController::class, 'method1'];
var_dump(is_callable($callback) === true);

$callback = ['DummyController', 'method1'];
var_dump(is_callable($callback) === true);
```
But I mean it's logic that this is a callable when the array is included in the [callable type](https://www.php.net/manual/de/language.types.callable.php).
I think you can close this issue now.

**Comment by skipperbent** [comment]
@DeveloperMarius Think the majority without reading the documentation will think that `is_callable` will check if a variable is a function (hence callable). I guess the correct way for checking for a function is `($variable instanceof \Closure)`.

**Comment by DeveloperMarius** [comment]
Yes, you are right. I mean I didn't know this eather until I read the documentation today.
Your check is better yes, but when you are checking for a function before calling `call_user_func_array`, `is_callable` is the right way to do this.

**Comment by Carsak** [comment]
Downloaded new version 4.3.2.3.
Tested with `SimpleRouter::post('/todo/add/', [\App\Controller\TodoController::class, 'add']);`

Message about "deprecate" disappeared
