### ISSUE TITLE
Getting a 302 on a route

### ISSUE THREAD

**Issue by filiptronicek** [skipperbent/simple-php-router#546]
I have a route, that is set up like this: 

```php
SimpleRouter::get('/admin/', function() {
    include_once "public/admin.php";
});
```
The problem is, that every time I visit this route I get a 302 to the same path, which means I get a redirection error. 
![image](https://user-images.githubusercontent.com/29888641/116896406-81bf3200-ac34-11eb-979a-ee774f509264.png)

This has to be done by the router because I don't set the status code anywhere in the file, I only set codes 200, 401, or 403.

I was wondering if it maybe tries to correct for a trailing slash or something and fails to do so? I don't really know to be honest.

**Comment by skipperbent** [comment]
The router doesn't redirect unless you have rewrite-urls or middlewares that interferes and changes the request. But there's no where it uses http-code `302`. The default http-code for the redirect is `301`.

- What version of the router are you using? 
- What webserver are you using, php version etc?
- What's the content's of `admin.php` - does it load if you die inside the function?

You can use the debug-info to see what routes are loaded and in what order by running:

```php
$debugInfo = SimpleRouter::startDebug();
echo sprintf('<pre>%s</pre>', var_export($debugInfo));
exit;
```

**Comment by skipperbent** [comment]
More info here:
https://github.com/skipperbent/simple-php-router#debugging

**Comment by filiptronicek** [comment]
Hi, I'm using version 4.3.3.0 of the router, which should be the latest one. This is happening on both Apache with PHP 7.4 as well as Apache with PHP 8.0 (both on Ubuntu).

**Comment by filiptronicek** [comment]
Ok, sorry to raise this issue because of such a dumb problem, I figured it was a problem in my code, where I am catching all 5 letter routes (I suppose I will need to implement that in the error logic)... thanks for the help!

**Comment by skipperbent** [comment]
That can happen to the best. I'm glad you got it working, that's what matters.

Have a nice day :)

/ Simon
