### ISSUE TITLE
Send form data and receive it as a parameter in the controller

### ISSUE THREAD

**Issue by davidribeiro05** [skipperbent/simple-php-router#547]
Hello, is it possible to send the form data and receive it via the controller parameter?

My Route is like this: 
`Router::post('/pessoa/criar', 'Pessoa@criar')->name('criar_pessoa');`

And my controller:
[    public function criar()
    {
    }](url)

Sorry for my bad English, I'm Brazilian. Thanks

**Comment by skipperbent** [comment]
That's no possible as the parameters is only for the route itself. However you could add this behavior by adding a custom ClassLoader and injecting `input->all()` when loading the method (see documentation for ClassLoader).

The intended behavior is to use the `InputHandler` for this exact purpose within your controller, for example: `input('form_element')` - or `input()->all(['element1', 'element2']);`.

**Comment by davidribeiro05** [comment]
Okay, I am going to try.

**Comment by skipperbent** [comment]
Good luck. If you have any further questions feel free to reopen or create another issue.

/ Simon
