### ISSUE TITLE
Nedd help with Class hitting

### ISSUE THREAD

**Issue by MrPresidentWhite** [skipperbent/simple-php-router#561]
Hi, i'm always get this error below:

`Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\ClassNotFoundHttpException: Class "\App\Controllers\App\Controllers\ServiceController" does not exist in /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php:19 Stack trace: #0 /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php(95): Pecee\SimpleRouter\ClassLoader\ClassLoader->loadClass() #1 /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(410): Pecee\SimpleRouter\Route\Route->renderRoute() #2 /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(339): Pecee\SimpleRouter\Router->routeRequest() #3 /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(68): Pecee\SimpleRouter\Router->start() #4 /data/wwwroot/index.php(15): Pecee\SimpleRouter\SimpleRouter::start() #5 {main} thrown in /data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php on line 19`

this is my index file:

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require 'vendor/autoload.php';

use Pecee\SimpleRouter\SimpleRouter;

require_once 'helpers.php';
require_once 'routes.php';

SimpleRouter::setDefaultNamespace('\App\Controllers');

SimpleRouter::start();
```

this is my routes file:

```
<?php

use App\Controllers\ServiceController;
use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::get('/services', [ServiceController::class, 'showServices']);
```

and this is my controller file:

```
<?php


namespace App\Controllers;


class ServiceController
{

    public static function showServices(): string
    {
        return "Hallo";
    }
}
```

what am I doing wrong here? I think I did everything just like in the wiki. Can you help me please?

**Comment by skipperbent** [comment]
Methods in the controller should not be static. Try changing that and see if the router can find the method.

**Comment by MrPresidentWhite** [comment]
Many thanks for the quick response. I'll try tomorrow. It's 3:30 in the morning and I should get some sleep. I'll be in touch as soon as I've tried it.

**Comment by skipperbent** [comment]
No problem - happy to help. By the error it does sound like there's a problem with the default-namespace in the router.

`Class "\App\Controllers\App\Controllers\ServiceController" does not exist`

Looks like it's appending the namespace where it's not necessary.

Please let me know if the route works without class hinting like so:

```php
SimpleRouter::get('/services', 'ServiceController@showServices');
```

If above works, then it's a problem with class hinting + default namespace.

**Comment by MrPresidentWhite** [comment]
hello, i have done all changes like you said and this error continues
![Screenshot_895](https://user-images.githubusercontent.com/38688739/121351416-0dab3480-c92c-11eb-9623-0fa840aa5550.png)

**Comment by skipperbent** [comment]
Can you try to update to the latest version 4.3.6.0?

**Routes.php**
```php
Router::setDefaultNamespace('Hello\Controllers');
Router::get('/media', 'MediaController@home')->name('media');
```

**Controller:**
```php
namespace Hello\Controllers;
class MediaController extends Controller {
    public function home(): string
    {
        return 'Hello World';
    }
}
```

If the error persists, you'll have to provide some debug-info for me to make it easier to debug:

https://github.com/skipperbent/simple-php-router#debug-information

Hope it helps.

/ Simon

**Comment by MrPresidentWhite** [comment]
this are the debug infos from the example debug code 

`array ( 'url' => Pecee\Http\Url::__set_state(array( 'originalUrl' => '/services', 'scheme' => 'https', 'host' => 'api.weber-motors.com', 'port' => NULL, 'username' => NULL, 'password' => NULL, 'path' => '/services/', 'params' => array ( ), 'fragment' => NULL, )), 'method' => 'get', 'host' => 'api.weber-motors.com', 'loaded_routes' => array ( 0 => Pecee\SimpleRouter\Route\RouteUrl::__set_state(array( 'url' => '/services/', 'name' => NULL, 'regex' => NULL, 'filterEmptyParams' => true, 'defaultParameterRegex' => NULL, 'paramModifiers' => '{}', 'paramOptionalSymbol' => '?', 'urlRegex' => '/^%s\\/?$/u', 'group' => NULL, 'parent' => NULL, 'callback' => 'ServiceController@showServices', 'defaultNamespace' => NULL, 'namespace' => NULL, 'requestMethods' => array ( 0 => 'get', ), 'where' => array ( ), 'parameters' => array ( ), 'originalParameters' => array ( ), 'middlewares' => array ( ), )), ), 'all_routes' => array ( 0 => Pecee\SimpleRouter\Route\RouteUrl::__set_state(array( 'url' => '/services/', 'name' => NULL, 'regex' => NULL, 'filterEmptyParams' => true, 'defaultParameterRegex' => NULL, 'paramModifiers' => '{}', 'paramOptionalSymbol' => '?', 'urlRegex' => '/^%s\\/?$/u', 'group' => NULL, 'parent' => NULL, 'callback' => 'ServiceController@showServices', 'defaultNamespace' => NULL, 'namespace' => NULL, 'requestMethods' => array ( 0 => 'get', ), 'where' => array ( ), 'parameters' => array ( ), 'originalParameters' => array ( ), 'middlewares' => array ( ), )), ), 'boot_managers' => array ( ), 'csrf_verifier' => NULL, 'log' => array ( 0 => array ( 'message' => 'Router starting', 'time' => '0.0012178421', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php', 'line' => 83, 'function' => 'start', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 1 => array ( 'message' => 'Loading routes', 'time' => '0.0012290478', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 2 => array ( 'message' => 'Processing routes', 'time' => '0.0012319088', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 285, 'function' => 'processRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 3 => array ( 'message' => 'Processing route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0012378693', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 285, 'function' => 'processRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 4 => array ( 'message' => 'Finished loading routes', 'time' => '0.0012419224', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 5 => array ( 'message' => 'Routing request', 'time' => '0.0012438297', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 6 => array ( 'message' => 'Matching route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0012478828', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 7 => array ( 'message' => 'Loading middlewares', 'time' => '0.0012688637', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 395, 'function' => 'loadMiddleware', 'class' => 'Pecee\\SimpleRouter\\Route\\LoadableRoute', 'type' => '->', ), ), 8 => array ( 'message' => 'Finished loading middlewares', 'time' => '0.0012710094', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 395, 'function' => 'loadMiddleware', 'class' => 'Pecee\\SimpleRouter\\Route\\LoadableRoute', 'type' => '->', ), ), 9 => array ( 'message' => 'Starting rendering route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0012769699', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 10 => array ( 'message' => 'Parsing parameters', 'time' => '0.0012788773', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 11 => array ( 'message' => 'Finished parsing parameters', 'time' => '0.0012810230', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 12 => array ( 'message' => 'Loading class ServiceController', 'time' => '0.0012929440', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 13 => array ( 'message' => 'Starting exception handling for "Pecee\\SimpleRouter\\Exceptions\\ClassNotFoundHttpException"', 'time' => '0.0014858246', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 430, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 14 => array ( 'message' => 'Finished exception handling - exception not handled, throwing', 'time' => '0.0014929771', 'trace' => array ( 'file' => '/data/wwwroot/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 430, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), ), 'event_handlers' => array ( ), 'router_output' => NULL, 'library_version' => false, 'php_version' => '7.4.19', 'server_params' => array ( 'user' => 'www', 'home' => '/data/wwwroot', 'http_accept_language' => 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7', 'http-accept-language' => 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7', 'http_accept_encoding' => 'gzip, deflate, br', 'http-accept-encoding' => 'gzip, deflate, br', 'http_sec_fetch_dest' => 'document', 'http-sec-fetch-dest' => 'document', 'http_sec_fetch_user' => '?1', 'http-sec-fetch-user' => '?1', 'http_sec_fetch_mode' => 'navigate', 'http-sec-fetch-mode' => 'navigate', 'http_sec_fetch_site' => 'none', 'http-sec-fetch-site' => 'none', 'http_accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'http-accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'http_user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36', 'http-user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36', 'http_upgrade_insecure_requests' => '1', 'http-upgrade-insecure-requests' => '1', 'http_dnt' => '1', 'http-dnt' => '1', 'http_sec_ch_ua_mobile' => '?0', 'http-sec-ch-ua-mobile' => '?0', 'http_sec_ch_ua' => '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"', 'http-sec-ch-ua' => '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"', 'http_cache_control' => 'no-cache', 'http-cache-control' => 'no-cache', 'http_pragma' => 'no-cache', 'http-pragma' => 'no-cache', 'http_x_real_ip' => '80.136.23.224', 'http-x-real-ip' => '80.136.23.224', 'http_x_forwarded_for' => '80.136.23.224', 'http-x-forwarded-for' => '80.136.23.224', 'http_x_forwarded_proto' => 'https', 'http-x-forwarded-proto' => 'https', 'http_x_forwarded_scheme' => 'https', 'http-x-forwarded-scheme' => 'https', 'http_host' => 'api.weber-motors.com', 'http-host' => 'api.weber-motors.com', 'redirect_status' => '200', 'redirect-status' => '200', 'server_name' => 'localhost', 'server-name' => 'localhost', 'server_port' => '80', 'server-port' => '80', 'server_addr' => '172.19.0.12', 'server-addr' => '172.19.0.12', 'remote_port' => '39414', 'remote-port' => '39414', 'remote_addr' => '172.19.0.2', 'remote-addr' => '172.19.0.2', 'server_software' => 'nginx/1.20.1', 'server-software' => 'nginx/1.20.1', 'gateway_interface' => 'CGI/1.1', 'gateway-interface' => 'CGI/1.1', 'request_scheme' => 'http', 'request-scheme' => 'http', 'server_protocol' => 'HTTP/1.1', 'server-protocol' => 'HTTP/1.1', 'document_root' => '/data/wwwroot', 'document-root' => '/data/wwwroot', 'document_uri' => '/index.php', 'document-uri' => '/index.php', 'request_uri' => '/services', 'request-uri' => '/services', 'script_name' => '/index.php', 'script-name' => '/index.php', 'content_length' => '', 'content-length' => '', 'content_type' => '', 'content-type' => '', 'request_method' => 'GET', 'request-method' => 'GET', 'query_string' => 's=/services', 'query-string' => 's=/services', 'script_filename' => '/data/wwwroot/index.php', 'script-filename' => '/data/wwwroot/index.php', 'fcgi_role' => 'RESPONDER', 'fcgi-role' => 'RESPONDER', 'php_self' => '/index.php', 'php-self' => '/index.php', 'request_time_float' => 1623249569.403005, 'request-time-float' => 1623249569.403005, 'request_time' => 1623249569, 'request-time' => 1623249569, ), )`

this is my composer,json

```
{
    "require": {
        "ext-json": "*",
        "pecee/simple-router": "^4.3"
    }
}

```

and if i'm changing my code to youre example, my IDE says this:

![Screenshot_896](https://user-images.githubusercontent.com/38688739/121376338-b9ab4a80-c941-11eb-9626-50596d768b18.png)

**Comment by skipperbent** [comment]
Please do `composer upgrade` to update to latest version.

Thanks for the debug-info.

Sorry for the typo, the correct method name is `SimpleRouter::setDefaultNamespace`.

- Does it work when upgrading?
- Does it work if you skip `setDefaultNamespace` and use the full namespace in the route instead? `Router::get('/member', '\Project\Controllers\MemberController@home');`
- Does the demo project work? (See: https://github.com/skipperbent/simple-router-demo)

/ Simon

**Comment by MrPresidentWhite** [comment]
this is what i get from the demo project:

`Fatal error: Uncaught Error: Class 'Demo\Router' not found in /data/wwwroot/public/index.php:9 Stack trace: #0 {main} thrown in /data/wwwroot/public/index.php on line 9`

**Comment by skipperbent** [comment]
When you clone the project you have to do a composer install otherwise all the dependencies won't be there.

**Comment by skipperbent** [comment]
If you cannot load Demo\Router then there's a problem with the composer autoload, most likely because it's hasn't been initialized.

**Comment by MrPresidentWhite** [comment]
if i go to the provided pages in the demo there always comes the error "File not found" or "Page not found"

**Comment by skipperbent** [comment]
Try going to /contact or any of the other routes defined in the routes.php. 

You are loading the error handler, so that's something.

Are you using the site on its own host like local.demo.com/contact?

What version of php are you using?

**Comment by MrPresidentWhite** [comment]
i am using the latest image of this docker container here https://hub.docker.com/r/skiychan/nginx-php7 an this is on my webserver with a subdomain

**Comment by skipperbent** [comment]
Php version is 7.4.19 as far as I can see.. that's strange why it won't load any classes.

I will try to download the container and see if I can recreate the issue

**Comment by skipperbent** [comment]
Hi again.

Just tested the container with the simple-router-demo and it works perfectly.

![2021-06-09_18-30-33](https://user-images.githubusercontent.com/634762/121393848-09ddd900-c951-11eb-9181-40e9124948ed.png)
![2021-06-09_18-30-20](https://user-images.githubusercontent.com/634762/121393861-0cd8c980-c951-11eb-87b1-f6c0dd394745.png)
![2021-06-09_18-31-39](https://user-images.githubusercontent.com/634762/121393869-0ea28d00-c951-11eb-8fbd-8191cec60927.png)

Just had to do some minor changes to the `/data/server/vhost/localhost.conf` so that the container pointed to the correct path within my project (`/data/www` points to the root of the simple-router-demo project).

**Comment by MrPresidentWhite** [comment]
Now it finally works after changing the nginx root directory. Thank you very much for your help.

**Comment by skipperbent** [comment]
Nice! I'm glad you finally got it working. Feel free to open another ticket if you encounter any other issues or have questions regarding the project.

/ Simon
