### ISSUE TITLE
setDefaultNamespace doesn't seem to be setting

### ISSUE THREAD

**Issue by AlexanderSchaller** [skipperbent/simple-php-router#565]
Apologies in advance if I am just being stupid and missing something... I upgraded to the newest release, and my class hinting broke (I was using the group method previously).  

When I try to set it via ::setDefaultNamespace it doesn't make a difference.

`SimpleRouter::setDefaultNamespace('\app\controllers');`
 
If I add the namespace to the method directly then it still works.  
`SimpleRouter::get('/', [\app\controllers\IndexController::class,'index']);`

Any advice for what I could be missing?

**Comment by skipperbent** [comment]
Please post the error you receive when navigating to `/` and the contents of your routes.php.

Also debug info would be helpful to see what routes the router has loaded.

https://github.com/skipperbent/simple-php-router#debug-information

**Comment by skipperbent** [comment]
setDefaultNamespace will not overwrite the namespace when using the class hint syntax `[controller::class, 'method']` as it most likely already has the full namespace. You'll have to use the 'Controller@method' syntax instead for the namespace to be inherited.

**Comment by AlexanderSchaller** [comment]
Error: 
`Class "IndexController" does not exist`

A sample of the routes.php

`use Pecee\SimpleRouter\SimpleRouter;

SimpleRouter::setDefaultNamespace('\app\controllers');

SimpleRouter::csrfVerifier(new \app\core\middlewares\CsrfVerifier());

SimpleRouter::group(['exceptionHandler' => \app\core\handlers\CustomExceptionHandler::class], function () {

    SimpleRouter::get('/rimg/{code}.png', [ImageController::class,'renderIMG']);

    //wrap the whole site in a maintenance middleware because it needs to be global
    SimpleRouter::group(['middleware' => app\core\middlewares\MaintenanceMiddleware::class], function () {

        // We want our 2FA page to live outside of the TFA wrapper to avoid endless redirects
        SimpleRouter::get('/twofactorauthentication', [AccountController::class,'twoFactorAuthPrompt']);
        SimpleRouter::post('/twofactorauthentication', [AccountController::class,'twoFactorAuthPromptProcess']);
        
        // Add 2FA middleware to the site globally
        SimpleRouter::group(['middleware' => app\core\middlewares\TFAMiddleware::class], function () {

            //public facing pages
            SimpleRouter::get('/', [IndexController::class,'index']);
         });
});`


I saw your second message, and `Controller@method` doesn't work either... same message.


Debug:

`array ( 'url' => Pecee\Http\Url::__set_state(array( 'originalUrl' => '/', 'scheme' => NULL, 'host' => 'finaloutpost.local', 'port' => NULL, 'username' => NULL, 'password' => NULL, 'path' => NULL, 'params' => array ( ), 'fragment' => NULL, )), 'method' => 'get', 'host' => 'finaloutpost.local', 'loaded_routes' => array ( ), 'all_routes' => array ( ), 'boot_managers' => array ( ), 'csrf_verifier' => app\core\middlewares\CsrfVerifier::__set_state(array( 'except' => array ( 0 => '/api/*', ), 'include' => NULL, 'tokenProvider' => Pecee\Http\Security\CookieTokenProvider::__set_state(array( 'token' => '4dc4474c11e94696f9ff0fb25ec4e437acbbb91b4df4ff5dc8e974bf222a75e8', 'cookieTimeoutMinutes' => 120, )), )), 'log' => array ( 0 => array ( 'message' => 'Router starting', 'time' => '0.0104970932', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php', 'line' => 83, 'function' => 'start', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 1 => array ( 'message' => 'Loading routes', 'time' => '0.0142500401', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 2 => array ( 'message' => 'Processing routes', 'time' => '0.0142631531', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 285, 'function' => 'processRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 3 => array ( 'message' => 'Finished loading routes', 'time' => '0.0142810345', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 4 => array ( 'message' => 'Routing request', 'time' => '0.0143191814', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 5 => array ( 'message' => 'Route not found: "/"', 'time' => '0.0143280029', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 6 => array ( 'message' => 'Starting exception handling for "Pecee\\SimpleRouter\\Exceptions\\NotFoundHttpException"', 'time' => '0.0181531906', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 450, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 7 => array ( 'message' => 'Finished exception handling - exception not handled, throwing', 'time' => '0.0181720257', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 450, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), ), 'event_handlers' => array ( ), 'router_output' => NULL, 'library_version' => false, 'php_version' => '8.0.3', 'server_params' => array ( 'redirect_unique_id' => 'YMXl7tqbbKU2KqRZppkA9QAAAAY', 'redirect-unique-id' => 'YMXl7tqbbKU2KqRZppkA9QAAAAY', 'redirect_status' => '200', 'redirect-status' => '200', 'unique_id' => 'YMXl7tqbbKU2KqRZppkA9QAAAAY', 'unique-id' => 'YMXl7tqbbKU2KqRZppkA9QAAAAY', 'http_host' => 'finaloutpost.local', 'http-host' => 'finaloutpost.local', 'http_accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'http-accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'http_upgrade_insecure_requests' => '1', 'http-upgrade-insecure-requests' => '1', 'http_cookie' => 'CSRF-TOKEN=4dc4474c11e94696f9ff0fb25ec4e437acbbb91b4df4ff5dc8e974bf222a75e8; _ga_7KEVS1PHET=GS1.1.1623580710.226.1.1623582074.0; _ga=GA1.2.1464677623.1598100201; _gid=GA1.2.367632208.1623580711; _fbp=fb.0.1598271705252.249549593; PHPSESSID=skrf5p4i04c6mv3apsiu87vv95', 'http-cookie' => 'CSRF-TOKEN=4dc4474c11e94696f9ff0fb25ec4e437acbbb91b4df4ff5dc8e974bf222a75e8; _ga_7KEVS1PHET=GS1.1.1623580710.226.1.1623582074.0; _ga=GA1.2.1464677623.1598100201; _gid=GA1.2.367632208.1623580711; _fbp=fb.0.1598271705252.249549593; PHPSESSID=skrf5p4i04c6mv3apsiu87vv95', 'http_user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15', 'http-user-agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15', 'http_accept_language' => 'en-us', 'http-accept-language' => 'en-us', 'http_accept_encoding' => 'gzip, deflate', 'http-accept-encoding' => 'gzip, deflate', 'http_connection' => 'keep-alive', 'http-connection' => 'keep-alive', 'path' => '/usr/bin:/bin:/usr/sbin:/sbin', 'dyld_library_path' => '/Applications/XAMPP/xamppfiles/lib', 'dyld-library-path' => '/Applications/XAMPP/xamppfiles/lib', 'server_signature' => '', 'server-signature' => '', 'server_software' => 'Apache/2.4.46 (Unix) OpenSSL/1.1.1j PHP/8.0.3 mod_perl/2.0.11 Perl/v5.32.1', 'server-software' => 'Apache/2.4.46 (Unix) OpenSSL/1.1.1j PHP/8.0.3 mod_perl/2.0.11 Perl/v5.32.1', 'server_name' => 'finaloutpost.local', 'server-name' => 'finaloutpost.local', 'server_addr' => '127.0.0.1', 'server-addr' => '127.0.0.1', 'server_port' => '80', 'server-port' => '80', 'remote_addr' => '127.0.0.1', 'remote-addr' => '127.0.0.1', 'document_root' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost', 'document-root' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost', 'request_scheme' => 'http', 'request-scheme' => 'http', 'context_prefix' => '', 'context-prefix' => '', 'context_document_root' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost', 'context-document-root' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost', 'server_admin' => 'you@example.com', 'server-admin' => 'you@example.com', 'script_filename' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/public/index.php', 'script-filename' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/public/index.php', 'remote_port' => '50439', 'remote-port' => '50439', 'redirect_url' => '/', 'redirect-url' => '/', 'redirect_query_string' => 'url=', 'redirect-query-string' => 'url=', 'gateway_interface' => 'CGI/1.1', 'gateway-interface' => 'CGI/1.1', 'server_protocol' => 'HTTP/1.1', 'server-protocol' => 'HTTP/1.1', 'request_method' => 'GET', 'request-method' => 'GET', 'query_string' => 'url=', 'query-string' => 'url=', 'request_uri' => '/', 'request-uri' => '/', 'script_name' => '/public/index.php', 'script-name' => '/public/index.php', 'php_self' => '/public/index.php', 'php-self' => '/public/index.php', 'request_time_float' => 1623582190.74359989166259765625, 'request-time-float' => 1623582190.74359989166259765625, 'request_time' => 1623582190, 'request-time' => 1623582190, )`

**Comment by skipperbent** [comment]
The debug doesn't contain any routes. Only thing I can see is that you added the csrfverifier. `all_routes` is empty.

Does it work if you place a route in the root (same place as where you call setCsrfVerifier)?

**Comment by AlexanderSchaller** [comment]
I get the same issue.  Here is the debug info

`array ( 'url' => Pecee\Http\Url::__set_state(array( 'originalUrl' => '/', 'scheme' => NULL, 'host' => 'finaloutpost.local', 'port' => NULL, 'username' => NULL, 'password' => NULL, 'path' => NULL, 'params' => array ( ), 'fragment' => NULL, )), 'method' => 'get', 'host' => 'finaloutpost.local', 'loaded_routes' => array ( 0 => Pecee\SimpleRouter\Route\RouteUrl::__set_state(array( 'url' => '/', 'name' => NULL, 'regex' => NULL, 'filterEmptyParams' => true, 'defaultParameterRegex' => NULL, 'paramModifiers' => '{}', 'paramOptionalSymbol' => '?', 'urlRegex' => '/^%s\\/?$/u', 'group' => NULL, 'parent' => NULL, 'callback' => array ( 0 => 'IndexController', 1 => 'index', ), 'defaultNamespace' => NULL, 'namespace' => NULL, 'requestMethods' => array ( 0 => 'get', ), 'where' => array ( ), 'parameters' => array ( ), 'originalParameters' => array ( ), 'middlewares' => array ( ), )), ), 'all_routes' => array ( 0 => Pecee\SimpleRouter\Route\RouteUrl::__set_state(array( 'url' => '/', 'name' => NULL, 'regex' => NULL, 'filterEmptyParams' => true, 'defaultParameterRegex' => NULL, 'paramModifiers' => '{}', 'paramOptionalSymbol' => '?', 'urlRegex' => '/^%s\\/?$/u', 'group' => NULL, 'parent' => NULL, 'callback' => array ( 0 => 'IndexController', 1 => 'index', ), 'defaultNamespace' => NULL, 'namespace' => NULL, 'requestMethods' => array ( 0 => 'get', ), 'where' => array ( ), 'parameters' => array ( ), 'originalParameters' => array ( ), 'middlewares' => array ( ), )), ), 'boot_managers' => array ( ), 'csrf_verifier' => app\core\middlewares\CsrfVerifier::__set_state(array( 'except' => array ( 0 => '/api/*', ), 'include' => NULL, 'tokenProvider' => Pecee\Http\Security\CookieTokenProvider::__set_state(array( 'token' => '4dc4474c11e94696f9ff0fb25ec4e437acbbb91b4df4ff5dc8e974bf222a75e8', 'cookieTimeoutMinutes' => 120, )), )), 'log' => array ( 0 => array ( 'message' => 'Router starting', 'time' => '0.0155839920', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php', 'line' => 83, 'function' => 'start', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 1 => array ( 'message' => 'Loading routes', 'time' => '0.0155930519', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 2 => array ( 'message' => 'Processing routes', 'time' => '0.0155961514', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 285, 'function' => 'processRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 3 => array ( 'message' => 'Processing route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0156052113', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 285, 'function' => 'processRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 4 => array ( 'message' => 'Finished loading routes', 'time' => '0.0156090260', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 327, 'function' => 'loadRoutes', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 5 => array ( 'message' => 'Routing request', 'time' => '0.0156490803', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 6 => array ( 'message' => 'Matching route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0156531334', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 339, 'function' => 'routeRequest', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 7 => array ( 'message' => 'Loading middlewares', 'time' => '0.0156781673', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 395, 'function' => 'loadMiddleware', 'class' => 'Pecee\\SimpleRouter\\Route\\LoadableRoute', 'type' => '->', ), ), 8 => array ( 'message' => 'Finished loading middlewares', 'time' => '0.0156800747', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 395, 'function' => 'loadMiddleware', 'class' => 'Pecee\\SimpleRouter\\Route\\LoadableRoute', 'type' => '->', ), ), 9 => array ( 'message' => 'Starting rendering route "Pecee\\SimpleRouter\\Route\\RouteUrl"', 'time' => '0.0156860352', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 10 => array ( 'message' => 'Parsing parameters', 'time' => '0.0157220364', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 11 => array ( 'message' => 'Finished parsing parameters', 'time' => '0.0157251358', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 12 => array ( 'message' => 'Loading class IndexController', 'time' => '0.0163381100', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 410, 'function' => 'renderRoute', 'class' => 'Pecee\\SimpleRouter\\Route\\Route', 'type' => '->', ), ), 13 => array ( 'message' => 'Starting exception handling for "Pecee\\SimpleRouter\\Exceptions\\ClassNotFoundHttpException"', 'time' => '0.0197370052', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 430, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), 14 => array ( 'message' => 'Finished exception handling - exception not handled, throwing', 'time' => '0.0197501183', 'trace' => array ( 'file' => '/applications/XAMPP/xamppfiles/htdocs/thefinaloutpost/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php', 'line' => 430, 'function' => 'handleException', 'class' => 'Pecee\\SimpleRouter\\Router', 'type' => '->', ), ), ), 'event_handlers' => array ( ), 'router_output' => NULL,`

Everything was working before I did composer update so I'm not sure what is up...

**Comment by skipperbent** [comment]
I can see the route in the debug info you just posted. So the router can see the route. But it doesn't see all your other routes/groups

**Comment by AlexanderSchaller** [comment]
The route is there but I still get the "class not found" error.  Is there a change in the update that would hide the other stuff?

**Comment by skipperbent** [comment]
No, it should see all or routes - regardless of whether they match the url or not. Especially the groups as they're always rendered.

What error do you get when navigation to the /. Also you need to use the syntax (string)'IndexController@index'

If you can give me access to your project i can try to see if I can locate the error

**Comment by AlexanderSchaller** [comment]
I get the error `Call to a member function getUrlCopy() on null`.  

I can add you to the project repository... is it okay if I email you directly as it is a private project?

**Comment by skipperbent** [comment]
> I get the error `Call to a member function getUrlCopy() on null`.
> 
> I can add you to the project repository... is it okay if I email you directly as it is a private project?

That's great. It means the route is loaded but some other error occured. Yes feel free to email me :)

**Comment by skipperbent** [comment]
For anyone reading this in the future scratching their alien grey head, the issue was caused by the `routes.php` using class hinting while not providing the full path for the classes. `SimpleRouter::setDefaultNamespace` namespaces are NOT appended when using class hinting, as the full class name is expected. 

```php
// Short names
use App\Controllers\Controller as Controller; // <-- missing this
SimpleRouter::get('/', [Controller::class, 'method']);

// Alternative
SimpleRouter::get('/', [App\Controllers\Controller::class, 'method']);
```

To load a controller without knowing the namespace, use the simple method instead:

```php
SimpleRouter::get('/', 'Controller@method');
```

Over and out

/ skipperbent
