### ISSUE TITLE
Get trailing path of catch-all route.

### ISSUE THREAD

**Issue by ericmackrodt** [skipperbent/simple-php-router#566]
Hello,

I've been using Simple PHP router for the last week and I'm really liking it, but I have an issue with catch-all routes.
My last route is supposed to get anything that falls on it because I load the information from markdown files.
The issues is that, using the regex in the route, I can match the route but I can't get the path from that route.

This is what my route looks like:

```
SimpleRouter::get('/', function () use ($renderPage) {
  echo "hello";
})->setMatch('/(.+)/is');
```

If I browse to `http://localhost:8000/guides/webbrowsing`, I do get the `hello` message.

But if I try to load a parameter like this:

```
SimpleRouter::get('/', function ($page) use ($renderPage) {
  echo var_dump($page);
})->setMatch('/(.+)/is');
```

I get the following error:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function {closure}(), 0 passed and exactly 1 expected in /Users/.../routes.php:38
```

I need it to echo the route `guides/webbrowsing`;

In express (node js), I have the option to do the following:
```
app.get("/*", function (req, res) {
  const urlPath = req.params[0];
  console.log(urlPath); // Logs guides/webbrowsing
});
```

I want to be able to do the same, does anyone know how to achieve that?

Thank you!

**Comment by skipperbent** [comment]
Thanks, I'm glad you like the project and can find it useful, that's what's matters.

You're doing it right, it sounds like the router has issues with catching that parameter in your regex.

Can you try to wrap the route in a group like so to see if the parameter is found?

```php
SimpleRouter::group(['defaultParameterRegex' => '.+'], function() {

    // Your route here...

});
```

Obviously the above is not ideal, but it will help me see debug if the issue is caused by the defaultParametersRegex not matching.

**Comment by skipperbent** [comment]
```php
/* /tester/hello/motto -> $results = hello/motto */

$results = '';
TestRouter::get('/tester/{param}', function ($param = null) use($results) {
            return $results = $param;
}, ['defaultParameterRegex' => '.+'])->setMatch('/(.*)/i');
```

Got it working like this. But i'll investigate why it's not working as intended. But the above should help you for now.

**Comment by skipperbent** [comment]
Hi @ericmackrodt .

I've made a patch for the issue and it's available if you upgrade to version Version 4.3.6.1.

Let me know if it resolves the issue. Thanks!

Have a nice day!

/ skipperbent

**Comment by ericmackrodt** [comment]
Hi @skipperbent 
It seems to be working!
But the `setMatch` method seems like it was removed from the IRoute interface.
Other than that, it's working great!

**Comment by skipperbent** [comment]
> Hi @skipperbent
> It seems to be working!
> But the `setMatch` method seems like it was removed from the IRoute interface.
> Other than that, it's working great!

I'm glad to hear it's working again!

You can find the `setMatch` on the `ILoadableRoute` interface. `IRoute` is for all routes including the ones that are not loaded like groups. `ILoadableRoute` and the `LoadableRoute` class is the interface that contains the `setMatch` functionality.
