### ISSUE TITLE
Make root to controller how has a dependency injection?

### ISSUE THREAD

**Issue by major200322** [skipperbent/simple-php-router#570]
Hi :)
  
first of all, I would like to thank all who contribute to this project :+1:  

So need to create Root to the controller how has dependency injection 

`SimpleRouter::get('/blogs', [IndexController::class, 'showBlog']);`

`    /**
     * indexController constructor.
     */
    public function __construct(PostsService $postService)`
    
  obviously, I didn't find any example

**Comment by skipperbent** [comment]
Hi.

I'm glad you like the project! It warms my cold little heart that someone out there in other dark basements find it useful :)

Not sure I understand the question correctly, so forgive if I'm misunderstanding - but it sounds like you want to integrate some kind of dependency injection.

You'll have to setup the dependency injection yourself based on whatever framework you're using.

**Take a look at custom class-loaders:**
https://github.com/skipperbent/simple-php-router#custom-class-loader

Class loaders are called each time the router is asking for a class/method.

**Here's an example on integrating with php-di:**

```php
use Pecee\SimpleRouter\Exceptions\ClassNotFoundHttpException;

class MyCustomClassLoader implements IClassLoader
{

    protected $container;

    public function __construct()
    {
        // Create our new php-di container
        $this->container = (new \DI\ContainerBuilder())
                    ->useAutowiring(true)
                    ->build();
    }

    /**
     * Load class
     *
     * @param string $class
     * @return object
     * @throws NotFoundHttpException
     */
    public function loadClass(string $class)
    {
        if (class_exists($class) === false) {
            throw new NotFoundHttpException(sprintf('Class "%s" does not exist', $class), 404);
        }

		try {
			return $this->container->get($class);
		} catch (\Exception $e) {
			throw new NotFoundHttpException($e->getMessage(), (int)$e->getCode(), $e->getPrevious());
		}
    }
    
    /**
     * Called when loading class method
     * @param object $class
     * @param string $method
     * @param array $parameters
     * @return object
     */
    public function loadClassMethod($class, string $method, array $parameters)
    {
		try {
			return $this->container->call([$class, $method], $parameters);
		} catch (\Exception $e) {
			throw new NotFoundHttpException($e->getMessage(), (int)$e->getCode(), $e->getPrevious());
		}
    }

    /**
     * Load closure
     *
     * @param Callable $closure
     * @param array $parameters
     * @return mixed
     */
    public function loadClosure(callable $closure, array $parameters)
    {
		try {
			return $this->container->call($closure, $parameters);
		} catch (\Exception $e) {
			throw new NotFoundHttpException($e->getMessage(), (int)$e->getCode(), $e->getPrevious());
		}
    }
}
```

**In your routes.php:**

```php
SimpleRouter::setCustomClassLoader(new MyCustomClassLoader());
```

Hope it helps.

/ skipperbent

**Comment by major200322** [comment]
Ok, I will try this :) thank you for your help

**Comment by skipperbent** [comment]
@major200322 No problem - I'm happy to help.

Good luck!

/ skipperbent
