### ISSUE TITLE
Is there an ajax request method?

### ISSUE THREAD

**Issue by Venloress** [skipperbent/simple-php-router#572]
I'm wondering if there is an ajax request method.
or how can i do it myself... ?

**Comment by HariharanUmapathi** [comment]
> I'm wondering if there is an ajax request method.
> or how can i do it myself... ?

1. You don't need ajax request method

2.create a ajax handler function in your project

Make call that function add a route to trigger that function 

//Ajax get handler

SimpleRouter::get("/ajax/controller/{resource}",function (){ 
require_once "my_ajax_controller.php";
ajax_controller(resource);
}

**Comment by skipperbent** [comment]
> I'm wondering if there is an ajax request method.
> or how can i do it myself... ?

Hi. Ajax can have multiple request-methods: `GET`, `POST`, `PUT` etc. You'll have to create the routes yourself (see the documentation).

You can check if the current request is Ajax by using `request()->isAjax`.
