### ISSUE TITLE
Custom error handler

### ISSUE THREAD

**Issue by Venloress** [skipperbent/simple-php-router#573]
Hi there, i couldn't do custom error handling.
eg 403.... An example is given for 404 but I don't fully understand.

**Comment by skipperbent** [comment]
Please read this part of the documentation:

https://github.com/skipperbent/simple-php-router#using-custom-exception-handlers.

Heres a simple example of how to catch 403 for ALL routes. If you want customize the way exceptions are handled for each of your routes, please take a look at the custom exception handler class.

Here's a very basic example. In the example below the routes `/not-found` and `/forbidden` have to exist in your `routes.php`.

```php
Router::error(function(Request $request, \Exception $exception) {

    switch($exception->getCode()) {
        // Page not found
        case 404:
            response()->redirect('/not-found');
        // Forbidden
        case 403:
            response()->redirect('/forbidden');
    }
    
});
```

If you do not want a redirect but load a class@method instead, use this instead

```php
$request->setRewriteCallback('ErrorController@notFound');
```

**Comment by Venloress** [comment]
Thanks, so how can i set group specific error page.

**Comment by skipperbent** [comment]
Hi again,

Create your custom exception handler class and add it to your group like so:

```php

SimpleRouter::group(['exceptionHandler' => \Demo\Handlers\CustomExceptionHandler::class], function() {

    // Your routes here

});
```

/ skipperbent

**Comment by Venloress** [comment]
Does not work well in groups within group.

**Comment by skipperbent** [comment]
By default the router will merge any `exceptionHandler` classes with ones inherited from parent groups.

I've created a patch that adds a settings-attribute that will prevent this feature and ignore any inherited handlers.

I will notify you once the new version is released.

**Comment by skipperbent** [comment]
If you update to the latest version 4.3.7.1 - there's a new group attribute (`'mergeExceptionHandlers' => false`) that will prevent the router from rendering any inherited handlers - which will *hopefully* resolve your issue:

https://github.com/skipperbent/simple-php-router#prevent-merge-of-parent-exception-handlers

**Example:**

```php
SimpleRouter::group(['prefix' => '/', 'exceptionHandler' => \Demo\Handlers\CustomExceptionHandler::class], function() {
    // Your routes here
   SimpleRouter::group(['prefix' => '/admin', 'exceptionHandler' => \Demo\Handlers\DefaultExceptionHandler::class, 'mergeExceptionHandlers' => false], function() {
        // Your routes here
   });
});
```

Let me know if it fixes your issue.

/skipperbent

**Comment by Venloress** [comment]
Yes, this works. But when I use it as `/adminsasd` it still sends it to the admin error.
/adminsasd => `custom 404`

must be;
/adminsasd => `default 404`
/admin/sadas =>  `custom 404`

Also thanks for the new feature. Other than that everything is very nice

**Comment by skipperbent** [comment]
@Venloress Happy to hear you got it working.

Seems like the `/adminsasd` triggering `/admin/` group-prefix is an unrelated issue. I'm creating a patch to resolve the issue that will be available shortly.

**Comment by skipperbent** [comment]
Please check to see if version 4.3.7.2 has resolved the issue with `/adminsasd` triggering your `/admin` prefix.

Thanks!

/skipperbent

**Comment by Venloress** [comment]
So beautiful now. Thank you for your interest

**Comment by skipperbent** [comment]
I'm glad you got it working!

Thanks for taking the time to report the issues. If you need any further assistance feel free to create a new ticket.

/skipperbent
