### ISSUE TITLE
Catching javascript fetch request

### ISSUE THREAD

**Issue by Venloress** [skipperbent/simple-php-router#585]
I am sending data with javascript fetch. How can I capture this on the router?
Is there a function like Request()->isAjax() ?

**Comment by DeveloperMarius** [comment]
Hey,

why do you only want to catch js requests?
You can catch a request using a normal route and then check is it is an ajax request `request()->isAjax()`. If not, you can return an error.

~ Marius

**Comment by Venloress** [comment]
i already do that. but request()->getHeader('http-x-requested-with') returns empty

my codes;
php
```php
if (request()->isAjax())
    return 'test';
return request()->getHeader('http-x-requested-with');
```
javascript
```js
axios.post('/web/login', {
    username: 'test'
}).then(function (response) {
    console.log(response);
});
```

**Comment by DeveloperMarius** [comment]
Okay.
Have you tried to get the header `requested-with` or `x-requested-with`?
Are they empty too?
Sometimes this is a bit wired^^
It this doesn't work maby print all headers received by the request and look over them manually.

~ Marius

**Comment by Venloress** [comment]
ohh ok, i edited my javascript code and found the right path. Thank you for taking care of my problem.
thanks to you...

solution =>`headers: { 'X-Requested-With': 'XMLHttpRequest' }` 
```js
axios({
    method: 'post',
    headers: {'X-Requested-With': 'XMLHttpRequest'},
    url: '/web/login',
    data: {
        username: 'text',
        lastName: 'Flintstone'
    }
}).then(function (response) {
    console.log(response);
});
```
