### ISSUE TITLE
Error 404 and Status Code in Browser Header

### ISSUE THREAD

**Issue by mauroagr** [skipperbent/simple-php-router#588]
Hi,
I am try to  create pages for 404 like the example below.
``` 
Router::error(function(Request $request, \Exception $exception) {
            if ($exception instanceof NotFoundHttpException && $exception->getCode() === 404) {
                echo $exception->getCode();
            }
});
```
They working fine, show the 404 code....when add the code, load page.
But, the status code in browser headers , stay return 200 and not 404.
How i can set the specific header for browser?
Thanks
Mauro

**Comment by skipperbent** [comment]
Check the Response object.

`response()->httpCode(404)`

Something like that

**Comment by mauroagr** [comment]
I test using this code.
``` 
Router::error(function(Request $request, \Exception $exception) {
    switch($exception->getCode()) {
        // Page not found
        case 404:
            $error = new \Front\ErrorController();
            $error->error();
        case 403:
            // response()->redirect('/error/404/');
    }

});
```
The content from error 404 page are loading right, but the header stay returning 200, showing in test below.
 
![image](https://user-images.githubusercontent.com/5348884/131595788-ab053a35-9ab0-4efb-9b5a-39aa396b67f1.png)

Thanks
Mauro

**Comment by skipperbent** [comment]
You need to specify the http code manually using the code below in your switch statement

`response()->httpCode(404)`

**Comment by mauroagr** [comment]
Hi,
Solved. 
I was putting in wrong place.
```
Router::error(function(Request $request, \Exception $exception) {
    switch($exception->getCode()) {
        // Page not found
        case 404:
            Router::response()->httpCode(404);
            $error = new \Front\ErrorController();
            $error->error();
        case 403:
            // response()->redirect('/error/404/');
    }
});
```
