### ISSUE TITLE
Group with optional parameter in prefix not matching

### ISSUE THREAD

**Issue by SunflowerFuchs** [skipperbent/simple-php-router#595]
A group with the prefix `'/{required}/{optional?}'` never matches, since the parameter replace in RouteGroup::matchRoute() only replaces required parameters.
https://github.com/skipperbent/simple-php-router/blob/749f252ffba98955311235cc2befc8ab742a151c/src/Pecee/SimpleRouter/Route/RouteGroup.php#L77

**Comment by DeveloperMarius** [comment]
Hello,
optional parameters in group routes are currently not possible.
I personally don't think that this would be a good feature, because it breaks your whole URL structure. But maby you can show me an example where it is usefull to imprement it and I change my oppinion.

~ Marius

**Comment by DeveloperMarius** [comment]
Hello,
if you don't need this functionality anymore, please close your issue.

~ Marius

**Comment by SunflowerFuchs** [comment]
Sorry, i forgot to reply.
We solved it differently in our application now, so we don't need this feature.
And you're correct, implementing this would break the URL structure too much, so it's better this way.
