### ISSUE TITLE
raw php input - not json but begins with { character

### ISSUE THREAD

**Issue by vrgblzs** [skipperbent/simple-php-router#599]
If I POST a raw stream that is not a json, but begins with a { character I got (v4.3.7.2):

PHP Fatal error:  Uncaught Error: Unsupported operand types in vendor/pecee/simple-router/src/Pecee/Http/Input/InputHandler.php:83

Found the bug in InputHandler.php @ row 82: 
if ($post !== false) 
should be 
if ($post !== null) 
as json_decode gives null (not false) if the string is not a valid json.

Thank you for this fine package!

**Comment by DeveloperMarius** [comment]
Hello,

thank you for the report.
I created the PR #608 to fix your issue.
Now we have to wait for @skipperbent to merge it into the master branch.

~ Marius

**Comment by vrgblzs** [comment]
Thanks!
