### ISSUE TITLE
path /

### ISSUE THREAD

**Issue by kilmerbit** [skipperbent/simple-php-router#601]
Hallo ? I have a problem like the following

Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/aaa/" in E:\xampp\htdocs\aaa\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php:454 Stack trace: #0 E:\xampp\htdocs\aaa\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php(343): Pecee\SimpleRouter\Router->routeRequest() #1 E:\xampp\htdocs\aaa\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php(69): Pecee\SimpleRouter\Router->start() #2 E:\xampp\htdocs\aaa\core\Framework.php(15): Pecee\SimpleRouter\SimpleRouter::start() #3 E:\xampp\htdocs\aaa\index.php(6): Kilmerbit\Framework::start() #4 {main} thrown in E:\xampp\htdocs\aaa\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php on line 454

This is my route code : Router::get('/', [AdminController::class, 'index']);

program will only run when I add basepath in each route
Router::get('/aaa/', [AdminController::class, 'index']); = '/'
Router::get('/aaa/home', [AdminController::class, 'index']); = '/home

Help me, how the program runs without having to add basepath to every route ?
i am using php 8.

Thanks very much

**Comment by parkerj** [comment]
You can set a base path for all your routes without adding it to every route. Check out the section, [Setting custom base path](https://github.com/skipperbent/simple-php-router#setting-custom-base-path).
