### ISSUE TITLE
Bad Request error when url's parameters contain "%" using regex

### ISSUE THREAD

**Issue by cdanielzt** [skipperbent/simple-php-router#635]
``` php
Route::get('/addon/{name}/{apikey}', function($name, $apikey){

    return response()->redirect("addons/addons.php?addon=$name&apikey=$apikey");

})->where(['apikey' => '[\w\-\@\%]+' ]);
```
On this route i got an Bad Request error when the apikey parameter contains '%' like `/addon/communitymap/bjV%3DN3n2e4nu`.

I would like the parameter to accept letters, numbers and these symbols `%` `@`  `_`  `-`

The regex works for any other symbol rather than `%`  

In summary:

This works:
`/addon/communitymap/bjVQ@XlSUkBhZmM`

This don't work:
`/addon/communitymap/bjVQ@XlSUkBh%ZmM`
`/addon/communitymap/bjVQ%XlSUkBh%ZmM`

**Comment by cdanielzt** [comment]
I have fixed it by adding `\=` to the accepted characters

**Comment by cdanielzt** [comment]
I have fixed it by adding \= to the accepted characters

**Comment by DeveloperMarius** [comment]
Hey,

yes, this is the correct way. You have to escape some characters in a RegEx.

~ Marius
