### ISSUE TITLE
Bugs not displayed 

### ISSUE THREAD

**Issue by Seotoolsdeveloper** [skipperbent/simple-php-router#636]
I am creating an mvc using this router .
I am not able to see any errors and the app breaking .
How Can I show them

**Comment by DeveloperMarius** [comment]
Hello,

please provide your code so that we can help you.
What do you mean with errors? Errors with the router or errors in your app?

You can enable the debug mode of the router or use an exception handler.

~ Marius

**Comment by Seotoolsdeveloper** [comment]
errors in your app that is what I mean

**Comment by skipperbent** [comment]
Are you using the demo project? Might not be completely up to date give me a moment and I'll update it

**Comment by Seotoolsdeveloper** [comment]
I used the ExceptionHandler from it

**Comment by skipperbent** [comment]
> I used the ExceptionHandler from it
Did you register it in your routes.php file?

**Comment by Seotoolsdeveloper** [comment]
Yes. I have already done that 

`Route::group(['prefix' => folderprefix,'exceptionHandler' => \App\Handlers\HomeExceptionHandler::class, 'mergeExceptionHandlers' => false], function () {
       
        Route::post('/api/event', 'WebeventController@index');
        Route::get('/api/event', 'WebeventController@index');
    });`

**Comment by skipperbent** [comment]
Do just get a blank page? Is there any information in php_errors.log?

**Comment by Seotoolsdeveloper** [comment]
no info
 php_errors.log is not available either.
So I am not able to see any php general error. 

I think the router is disabling it by the exception maybe

**Comment by skipperbent** [comment]
If no exception handler is present, the exception will just be thrown like normal.
Do you see any exceptions without the exception-handler enabled? Or is errors completely disabled in your setup?

**Comment by skipperbent** [comment]
Please try this project, I just updated it and confirmed it works.

Exception thrown when visiting `/api/demo` (GET)

https://github.com/skipperbent/simple-router-demo

**Comment by Seotoolsdeveloper** [comment]
Its now working correctly . 
Thanks
The types :void  and :?string were the issue
