### ISSUE TITLE
PHP 8.1 Gives error DEPRECATED

### ISSUE THREAD

**Issue by Geckon01** [skipperbent/simple-php-router#657]
On Php 8.1 i get this error:
![image](https://user-images.githubusercontent.com/19799402/233594092-57bda9d3-b263-4694-91d7-ef317a3e1c78.png)
I've disabled deprecated warnings for time being, but maybe this should be fixed? I can try fixing this myself btw if you wish.

**Comment by skipperbent** [comment]
Thanks for reporting the issue, a fix will be available shortly

**Comment by skipperbent** [comment]
Issue has been resolved in version 5.3.0.2.

**Comment by Geckon01** [comment]
Thanks a lot!
