### ISSUE TITLE
Url params not working with Resource routes

### ISSUE THREAD

**Issue by benfiratkaya** [skipperbent/simple-php-router#666]
Hello I have a Resource route. When I try to print resource url I get wrong url.
`SimpleRouter::resource('/games', GameController::class)->name('games');`
`<?php echo url('games.edit', ["id" => 5]) ?>`
Result:
`/games/edit/`
Expected:
`/games/5/edit`

**Comment by skipperbent** [comment]
What is returned if you do this?

```
url('games.edit', [5])
```

**Comment by benfiratkaya** [comment]
> What is returned if you do this?
> 
> ```
> url('games.edit', [5])
> ```

Same. And there is not much detailed information about the resource controller on Wiki. It would be good to have more information on Wiki.

Laravel resource controller routes:
It would be better to use a similar structure.

Verb | URI | Action | Route Name
-- | -- | -- | --
GET | /photos/{photo}/comments | index | photos.comments.index
GET | /photos/{photo}/comments/create | create | photos.comments.create
POST | /photos/{photo}/comments | store | photos.comments.store
GET | /comments/{comment} | show | comments.show
GET | /comments/{comment}/edit | edit | comments.edit
PUT/PATCH | /comments/{comment} | update | comments.update
DELETE | /comments/{comment} | destroy | comments.destroy

**Comment by benfiratkaya** [comment]
Also you can add except method for resource routes. 
Like this:
`SimpleRouter::resource('/games', GameController::class)->name('games')->except(["show", "destroy"]);`

**Comment by skipperbent** [comment]
I will have to look into why it's not working as intended, the reason I asked you to try without naming the parameter was to see if it was a problem with the parameters. By not defining a name it should add the value to the first parameter found regardless if the name matche or not, which it doesn't for some reason.

What version of the library are you using?

**Comment by benfiratkaya** [comment]
> I will have to look into why it's not working as intended, the reason I asked you to try without naming the parameter was to see if it was a problem with the parameters. By not defining a name it should add the value to the first parameter found regardless if the name matche or not, which it doesn't for some reason.
> 
> What version of the library are you using?

latest version

**Comment by skipperbent** [comment]
It should be working as intended on version 5.3.0.4. (readme still needs work, i'll save that joy for later).

**Comment by benfiratkaya** [comment]
It's not working as expected. I think there is a cache issue. When I call url('games.update', ['id' => 1]) after calling url('games.store') it gives the same output as my first call.

**Comment by benfiratkaya** [comment]
Weird output:
```
/games/2/edit/edit/
/games/1/edit/
/games/6/edit/
```

```php
	echo url('games.edit', ['id' => 2]);
	echo "\n";
	echo url('games.update', ['id' => 1]);
	echo "\n";
	echo url('games.store');
```

**Comment by skipperbent** [comment]
> Weird output:
> 
> ```
> /games/2/edit/edit/
> /games/1/edit/
> /games/6/edit/
> ```
> 
> ```
> 	echo url('games.edit', ['id' => 2]);
> 	echo "\n";
> 	echo url('games.update', ['id' => 1]);
> 	echo "\n";
> 	echo url('games.store');
> ```

That's very weird, especially since it's not caught by the phpunit test i added. I wonder where it gets id =6 from in the last url. Do you call anything with id 6 in your code previous to this that could help me debug?

**Comment by benfiratkaya** [comment]
> > Weird output:
> > ```
> > /games/2/edit/edit/
> > /games/1/edit/
> > /games/6/edit/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 	echo url('games.edit', ['id' => 2]);
> > 	echo "\n";
> > 	echo url('games.update', ['id' => 1]);
> > 	echo "\n";
> > 	echo url('games.store');
> > ```
> 
> That's very weird, especially since it's not caught by the phpunit test i added. I wonder where it gets id =6 from in the last url. Do you call anything with id 6 in your code previous to this that could help me debug?

Yes I tried with id=6 at first. And that's how it stuck. Not updating.

**Comment by skipperbent** [comment]
First time you call the url() it gives the correct one? But not afterwards?

**Comment by skipperbent** [comment]
I see my unit-test used the same parameter value for all the urls, so that could explain why it "worked".
I've redone the findUrl method, it works with different parameters at least in the unit test. Hopefully it fixes it for you aswell.

Let's try again in version 5.3.0.5

**Comment by benfiratkaya** [comment]
Its working! Thanks

**Comment by skipperbent** [comment]
> Its working! Thanks

I'm glad to hear, thanks for the detailed descriptions, it helped a lot friend.
