### ISSUE TITLE
route

### ISSUE THREAD

**Issue by AlexJMcloud** [skipperbent/simple-php-router#684]
When specifying the route '/{lang}/' and '/admin/' - the router selects the first match. Route '/admin/' - it completely ignores. How can I fix this behavior?

the same behavior is observed with other routes: '/{lang}/auth/login' and '/admin/auth/login/'.  However, their controller is different.

**Comment by AlexJMcloud** [comment]
I opened it here because I didn’t receive a response in the fork with version php 8.1.

**Comment by xJuvi** [comment]
Change the routes order. Load first the admin routes and then the dynamic language routes.

**Comment by AlexJMcloud** [comment]
> Change the routes order. Load first the admin routes and then the dynamic language routes.

I wrote my own router. Sometimes it’s easier to do it yourself than to research crap code.
