### ISSUE TITLE
README lacks "requirements" section

### ISSUE THREAD

**Issue by MarcinOrlowski** [skipperbent/simple-php-router#80]
README seem to lack "requirements" section (like min. PHP version, extensions etc).

**Comment by skipperbent** [comment]
Thanks!

This will be added to both `composer.json` and the documentation in next release.

**Comment by skipperbent** [comment]
This is fixed in version 1.7.

Please don't hesitate making issues if you experience any problems, have any ideas or features you'd like implemented.

**Comment by MarcinOrlowski** [comment]
I think requirements shall mention mod_rewrite as well with example of `.htaccess` like:

```
RewriteEngine on
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteCond %{SCRIPT_FILENAME} !-l
RewriteRule ^(.*)$ index.php/$1
```

also I do not see the point of suggested separation of routes from index.php file. There's clearly no benefits from my perspective and I'd consider updating README

Also I lack PHPDocs and info on crucial things like how read Request in Controller for example.

**Comment by skipperbent** [comment]
Well the mod_rewrite and .htaccess only apply if you use Apache as a webserver. But i guess it should state something like rewriting should be enabled and all requests should be redirected to index.php. Sorry in my tiny reptile brain that's just common sense; but I totally agree with you :)

Maybe an example project would make sense? 

No you're right. The routes.php and generally that section could easily confuse people, as most won't use that feature. It's only there to demonstrate how to integrate the router into whatever needs your project/framework has.

I'll reopen this until the requirements section is PERFECT :)

**Comment by skipperbent** [comment]
Hello again,

We've included a demo-project in the project and some instructions on how to get started, including documentation on server requirements and url-rewriting.

https://github.com/skipperbent/simple-php-router/tree/master/demo-project

Please create a new issue if you have further questions or problems.
