### ISSUE TITLE
Lack of tests?

### ISSUE THREAD

**Issue by MarcinOrlowski** [skipperbent/simple-php-router#81]
I just need a router for one of my project and Laravel compatibility of yours is a 'pro' for me, so I am going to evaluate your project, however I see no single test in here which frankly speaking scares me away a bit. How do you test your router?

**Comment by skipperbent** [comment]
I understand - the project is faily new, so the focus has really been on getting the features right and get it up and running - before implementing the tests. One can argue that the approach isn't right, but it did get us this far.

So far I've been the only one working on the project, so I really enjoy getting feedback. In regards to the tests i'll be adding this in the upcoming releases. I've already created tests for middlewares + basic routing. I'll update this ticket once all of them are ready :)

**Comment by skipperbent** [comment]
Test has been added and will continue to be added with each new release.

Thanks for your feedback.
