### ISSUE TITLE
Groups with placeholders cause parameter shift

### ISSUE THREAD

**Issue by MarcinOrlowski** [skipperbent/simple-php-router#84]
Not really sure if this is a bug or feature or side effect but this is somehow error prone:

```
SimpleRouter::group(['prefix' => 'v1/{item}/'], function () {
	SimpleRouter::get('/{foo}', function ($foo) {
		echo "Got {$foo}";
	});
});
```

as requesting `/v1/AAA/BBB` will result in `Got AAA` which is not what is expected.

**Comment by skipperbent** [comment]
This is because the parameters are delivered in order and not by name.. I like the idea though, so i'll fix this in the next release.

So in your example it would be

```php
SimpleRouter::group(['prefix' => '/v1/{item}'], function () {
    SimpleRouter::get('/{foo}', function ($item, $foo) {
        echo "Got {$foo}";
    });
});
```

And if it's nullable

```php
SimpleRouter::group(['prefix' => '/v1/{item?}'], function () {
    SimpleRouter::get('/{foo}', function ($item = null, $foo) {
        echo "Got {$foo}";
    });
});
```

**Comment by skipperbent** [comment]
Also its worth mentioning that groups does not support arguments in their functions, instead they will be passed to the routes inside. 

The reason for this is that every group has to be rendered on each page load so the router knows every URL possible for all routes; this happens so you can get the url for each route (for example via: `url('my.route.alias')`), even those that aren't loaded, for links etc.

So if some of the groups require arguments, they will fail when the route don't have those arguments. So instead the group passes on the arguments to the routes inside.

Hope it makes sense.

**Comment by MarcinOrlowski** [comment]
I see couple of usage patterns where this is a feature not a bug, yet what I miss here to use this intentionally is lack of thing similar to i.e. Laravel's `Input`. Still, this is not crucial really at the moment so it may stay on TODO list for while w/o much harm

**Comment by skipperbent** [comment]
I totally understand what you mean. I think the reason it doesn't have that feature is because the projects i've used the router in has gotten their own way of implementing ways of getting request parameters.

But I guess the `Request` class could have some way of retrieving input parameters and it definitely would make sense - unfortunately it doesn't at the moment. It's noted and i'll implement something simple - similar to the `Input` class from Laravel.

But for now you could create a small helper function

```php
function input($name, $defaultValue = null) {
    return (isset($_POST[$name]) ? $_POST[$name] : $defaultValue);
}
```

and then use that in your project.

I'll keep this issue open until the feature has been implemented in the `Request` class.

**Comment by skipperbent** [comment]
@MarcinOrlowski I've moved some `Input` related classes from my Framework to the router to meet the functionality you've requested about parameters.

Please see the section "Use the Input class to manage parameters" section in the documentation:
https://github.com/skipperbent/simple-php-router#using-the-input-class-to-manage-parameters

**Comment by skipperbent** [comment]
I'm closing this issue. Please reopen or create a new issue if you are still experiencing problems or have further questions or ideas.

Appreciate your feedback.
